/**************************************************************************
 * This file is generated by Java2C
 **copyright***************************************************************
 *************************************************************************/
#include "PosCtrl/MainController.h"
#include <string.h>  //because using memset()
#include <Jc/ReflectionJc.h>   //Reflection concept 
#include <Fwc/fw_Exception.h>  //basic stacktrace concept
#include "Fwc/fw_LogMessage.h"  //reference-association: msg
#include "Jc/StringJc.h"  //embedded type in class data
#include "PosCtrl/SetValueGenerator.h"  //new object
#include "PosCtrl/SetValueGenerator_ifc.h"  //reference-association: mySetValueGenerator
#include "PosCtrl/WaitThreadOrganizer.h"  //reference-association: waitCycleOrganizer1
#include "PosCtrl/WayActuator.h"  //reference-association: way1Actuator
#include "PosCtrl/WaySensor.h"  //reference-association: way1Sensor
#include "simPc/iRequireMainController.h"  //reference-association: broker


/* J2C: Method-table-references *********************************************************/
#ifndef SetValueGenerator_ifcMTBDEF
  #define SetValueGenerator_ifcMTBDEF
  typedef struct SetValueGenerator_ifcMTB_t { struct Mtbl_SetValueGenerator_ifc_t const* mtbl; struct SetValueGenerator_ifc_t* ref; } SetValueGenerator_ifcMTB;
#endif

#ifndef WaitThreadOrganizerMTBDEF
  #define WaitThreadOrganizerMTBDEF
  typedef struct WaitThreadOrganizerMTB_t { struct Mtbl_WaitThreadOrganizer_t const* mtbl; struct WaitThreadOrganizer_t* ref; } WaitThreadOrganizerMTB;
#endif

#ifndef WayActuatorMTBDEF
  #define WayActuatorMTBDEF
  typedef struct WayActuatorMTB_t { struct Mtbl_WayActuator_t const* mtbl; struct WayActuator_t* ref; } WayActuatorMTB;
#endif

#ifndef WaySensorMTBDEF
  #define WaySensorMTBDEF
  typedef struct WaySensorMTB_t { struct Mtbl_WaySensor_t const* mtbl; struct WaySensor_t* ref; } WaySensorMTB;
#endif


/**This class is the example main class to control a movement.

@author JcHartmut
*/


const char sign_Mtbl_MainController[] = "MainController"; //to mark method tables of all implementations

typedef struct MtblDef_MainController_t { Mtbl_MainController mtbl; MtblHeadJc end; } MtblDef_MainController;
 extern MtblDef_MainController const mtblMainController;
struct MainController_t* singleton_MainController = null;

/*Constructor */
struct MainController_t* ctorO_MainController(ObjectJc* othis, struct iRequireMainController_t* broker, struct LogMessageFW_t* msg1, struct WaitThreadOrganizer_t* waitCycleOrganizer, ThCxt* _thCxt)
{ MainController_s* ythis = (MainController_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_MainController");
  checkConsistence_ObjectJc(othis, sizeof(MainController_s), null, _thCxt);  
  setReflection_ObjectJc(othis, &reflection_MainController_s, sizeof(MainController_s));  
  //j2c: Initialize all class variables:
  {ObjectJc *newObj0_1=null; //J2C: temporary Objects for new operations
      
    //J2C: constructor for embedded element-ObjectJc
      init_ObjectJc(&(ythis->msgDispatcher.base.object), sizeof(ythis->msgDispatcher), 0); 
      ctorO_MsgDispatcher_MSG(/*static*/&(ythis->msgDispatcher.base.object), 100, 200, 28, 28, _thCxt);
    //J2C: constructor for embedded element-ObjectJc
      init_ObjectJc(&(ythis->logMsgFileCtrlValues.base.object), sizeof(ythis->logMsgFileCtrlValues), 0); 
      ctorO_LogMessageFile_MSG(/*static*/&(ythis->logMsgFileCtrlValues.base.object), s0_StringJc("testLog/ctrl$MMdd_HHmmss$.log"), 10, 1, null, null, getSharedFreeEntries_MsgDispatcher_MSG(& (ythis->msgDispatcher), _thCxt), _thCxt);
    //J2C: constructor for embedded element-ObjectJc
      init_ObjectJc(&(ythis->logMsgFileGC.base.object), sizeof(ythis->logMsgFileGC), 0); 
      ctorO_LogMessageFile_MSG(/*static*/&(ythis->logMsgFileGC.base.object), s0_StringJc("testLog/GC.log"), 0, 0, null, null, getSharedFreeEntries_MsgDispatcher_MSG(& (ythis->msgDispatcher), _thCxt), _thCxt);
    ythis->wWay = 10000;
    ythis->dWay1 = (int16_Y*)ctorO_ObjectArrayJc((newObj0_1 = alloc_ObjectJc( sizeof(ObjectArrayJc) + (1) * sizeof(int16), mIsLargeSize_objectIdentSize_ObjectJc, _thCxt)), 1, sizeof(int16),REFLECTION_int16, 0);  //J2C: assign a new ObjectArrayJc. ;
    ythis->addWay = 5;
    //J2C: constructor for embedded element-ObjectJc
      init_ObjectJc(&(ythis->pidCtrl1.base.object), sizeof(ythis->pidCtrl1), 0); 
      ctorO_PID_controller(/*static*/&(ythis->pidCtrl1.base.object), _thCxt);
    SETREFJc(ythis->pidCtrl2, & ((ythis->pidCtrl1).base.CtrlBase), CtrlBase_s);
    //J2C: constructor for embedded element-ObjectJc
      init_ObjectJc(&(ythis->targetReader.base.object), sizeof(ythis->targetReader), 0); 
      ctorO_ReadTargetFromText(/*static*/&(ythis->targetReader.base.object), _thCxt);
    //J2C: constructor for embedded element-ObjectJc
      init_ObjectJc(&(ythis->oamVariables.base.object), sizeof(ythis->oamVariables), 0); 
      ctorO_OamVariables(/*static*/&(ythis->oamVariables.base.object), _thCxt);
    //J2C: constructor for embedded element-ObjectJc
      init_ObjectJc(&(ythis->wayCtrlThread.base.object), sizeof(ythis->wayCtrlThread), 0); 
      ctorO_WayCtrlThread_MainController(ythis, &(ythis->wayCtrlThread.base.object), s0_StringJc("wayCtrl-1"), _thCxt);
    activateGarbageCollectorAccess_BlockHeapJc(newObj0_1, null);
  }
  { 
    StringJc msgCtrl = CONST_z_StringJc("1..999: 0x1; 5: 0x1; 0..1002:FileGC + FileCtrl; 2000..2010: FileGC; 2004: 0; 20..50:+CON;");   /*Example of a input for dispatching control. */
    struct SbY_errorBuffer_t { StringBufferJc sb; char _b[96]; }errorBuffer = { 0 };   /*If an error occurs, the buffer contains the error message plus input at fault position.*/
    StringJc sError; 
    
    ObjectJc *newObj1_1=null, *newObj1_2=null; //J2C: temporary Objects for new operations
    StringJc _persistring1_1=NULL_StringJc; //J2C: temporary persistent Strings
    
    singleton_MainController = ythis;
    ythis->msgDispatcherThread = ctorO_DispatcherThread_MsgDispatcher_MSG(& (ythis->msgDispatcher), (newObj1_1 = alloc_ObjectJc(sizeof_DispatcherThread_MsgDispatcher_MSG_s, 0, _thCxt)), 100, _thCxt);
    SETREFJc(ythis->waitCycleOrganizer, waitCycleOrganizer, WaitThreadOrganizer_s);//int maxNrofDispatchEntries = 100; //max number of different ranges in identifier numbers of messages.
    
    setOutputRoutine_MsgDispatcher_MSG(& (ythis->msgDispatcher), kMsgOutFile_MainController, s0_StringJc("FileCtrl"), true, & ((ythis->logMsgFileCtrlValues).base.LogMessageFW), _thCxt);
    setOutputRoutine_MsgDispatcher_MSG(& (ythis->msgDispatcher), kMsgOutFileGC_MainController, s0_StringJc("FileGC"), false, & ((ythis->logMsgFileGC).base.LogMessageFW), _thCxt);
    setOutputRange_MsgDispatcher_MSG(& (ythis->msgDispatcher), 0, 1000, 1 << kMsgOutFile_MainController, mAdd_MsgDispatcher_MSG, 4, _thCxt);//this.msg = LogMessage.convertFromMsgDispatcher(msgDispatcher);
    
    SETREFJc(ythis->msg, & ((ythis->msgDispatcher).base.LogMessageFW), LogMessageFW_i);
    msgCtrl = z_StringJc("1..999: 0x1; 5: 0x1; 0..1002:FileGC + FileCtrl; 2000..2010: FileGC; 2004: 0; 20..50:+CON;")/*J2C:non-persistent*/;
    
    //J2C: constructor for embedded fix-size-StringBuffer
    init_ObjectJc(&errorBuffer.sb.base.object, sizeof(StringBuilderJc) + 100 - 4, 0);
    ctorO_I_StringBuilderJc(&errorBuffer.sb.base.object, 100, _thCxt);
    sError = _persistring1_1 = persist_StringJc(setOutputFromString_MsgDispatcher_MSG(& (ythis->msgDispatcher), msgCtrl, & (errorBuffer.sb), _thCxt))/*J2C:non-persistent*/;
    if(sError.ptr__!= null) 
    { 
      
      ((Mtbl_LogMessageFW const*)getMtbl_ObjectJc(&(REFJc(ythis->msg))->base.object, sign_Mtbl_LogMessageFW) )->sendMsg(REFJc(ythis->msg), 1, "Error parsing msg dispatcher control string: %s.", "s", toString_StringBuilderJc(& ((errorBuffer.sb).base.object), _thCxt));
    }
    /**Sends test messages, to test the message dispatcher.*/
    ((Mtbl_LogMessageFW const*)getMtbl_ObjectJc(&(REFJc(ythis->msg))->base.object, sign_Mtbl_LogMessageFW) )->sendMsg(REFJc(ythis->msg), 1, "Test to console %s", "z", "test-string");
    ((Mtbl_LogMessageFW const*)getMtbl_ObjectJc(&(REFJc(ythis->msg))->base.object, sign_Mtbl_LogMessageFW) )->sendMsg(REFJc(ythis->msg), 1000, "Test to dispatched files. numbers= %d, %d", "BB", 1, 2);//this.msg = msg;
    
    ythis->mySetValueGenerator = & ((* (ctorO_SetValueGenerator(/*static*/(newObj1_2 = alloc_ObjectJc(sizeof_SetValueGenerator_s, 0, _thCxt)), REFJc(ythis->msg), & (ythis->oamVariables), _thCxt))).base.SetValueGenerator_ifc);
    SETREFJc(ythis->way1Sensor, ((Mtbl_iRequireMainController const*)getMtbl_ObjectJc(&(broker)->base.object, sign_Mtbl_iRequireMainController) )->requireWay1Sensor(&((broker)->base.object), _thCxt), WaySensor_s);
    SETREFJc(ythis->way2Sensor, ((Mtbl_iRequireMainController const*)getMtbl_ObjectJc(&(broker)->base.object, sign_Mtbl_iRequireMainController) )->requireWay2Sensor(&((broker)->base.object), _thCxt), WaySensor_s);
    SETREFJc(ythis->way1Actuator, ((Mtbl_iRequireMainController const*)getMtbl_ObjectJc(&(broker)->base.object, sign_Mtbl_iRequireMainController) )->requireWay1Actuator(&((broker)->base.object), _thCxt), WayActuator_s);
    SETREFJc(ythis->way2Actuator, ((Mtbl_iRequireMainController const*)getMtbl_ObjectJc(&(broker)->base.object, sign_Mtbl_iRequireMainController) )->requireWay2Actuator(&((broker)->base.object), _thCxt), WayActuator_s);
    activateGarbageCollectorAccess_BlockHeapJc(newObj1_1, null);
    activateGarbageCollectorAccess_BlockHeapJc(newObj1_2, null);
    activateGarbageCollectorAccess_BlockHeapJc(PTR_StringJc(_persistring1_1), null);
  }
  STACKTRC_LEAVE;
  return ythis;
}



/**Gets the set value in units mm*/
int16 getWaySetvalue_MainController(MainController_s* ythis, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("getWaySetvalue_MainController");
  
  { 
    
    { STACKTRC_LEAVE;
      return ythis->wWay;
    }
  }
  STACKTRC_LEAVE;
}


/**Gets the offset of the controller on input*/
int32 getWayOffset_MainController(MainController_s* ythis, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("getWayOffset_MainController");
  
  { 
    
    { STACKTRC_LEAVE;
      return ythis->dWay;
    }
  }
  STACKTRC_LEAVE;
}


/**prepares the working of the controller, called on startup from outside.*/
void prepare_MainController(MainController_s* ythis, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("prepare_MainController");
  
  { 
    
    wireFunction_MainController(ythis, _thCxt);
    test_ReadTargetFromText_F(& (ythis->targetReader), _thCxt);
  }
  STACKTRC_LEAVE;
}

void start_MainController(MainController_s* ythis, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("start_MainController");
  
  { 
    
    start_ThreadJc(& ((ythis->wayCtrlThread).base.super), -1, _thCxt);
  }
  STACKTRC_LEAVE;
}

void wireFunction_MainController(MainController_s* ythis, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("wireFunction_MainController");
  
  { 
    
    connectInput_PID_controller_F(& (ythis->pidCtrl1), ythis->dWay1, _thCxt);
    ythis->yOut2 = provideOutput_PID_controller_F(& (ythis->pidCtrl1), _thCxt);
  }
  STACKTRC_LEAVE;
}


/**This is the cyclic called method to execute the controlling. It is called from outside. */
void step_MainController(MainController_s* ythis, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("step_MainController");
  
  { 
    
    
  }
  STACKTRC_LEAVE;
}


/**Get the internal value of the integrator of the first way controller. */
float getWay11Intg_MainController(MainController_s* ythis, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("getWay11Intg_MainController");
  
  { 
    
    { STACKTRC_LEAVE;
      return getIntg_PID_controller_F(& (ythis->pidCtrl1), _thCxt);
    }
  }
  STACKTRC_LEAVE;
}


/**stores a next target point*/
bool setTarget_MainController(MainController_s* ythis, int16 targetValue, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("setTarget_MainController");
  
  { //:it is a delagation pattern. The outside user don't know the SetValueGenerator.
    
    bool isSet; 
    
    
    isSet = setTarget_i_SetValueGenerator_F(&((ythis->mySetValueGenerator)->base.object), targetValue, _thCxt);
    { STACKTRC_LEAVE;
      return isSet;
    }
  }
  STACKTRC_LEAVE;
}


void finalize_MainController_F(ObjectJc* othis, ThCxt* _thCxt)
{ MainController_s* ythis = (MainController_s*)othis;  //upcasting to the real class.
 STACKTRC_TENTRY("finalize_MainController_F");
  CLEAR_REFJc(ythis->msg);
  CLEAR_REFJc(ythis->waitCycleOrganizer);
  finalize_ObjectJc_F(&ythis->msgDispatcher.base.object, _thCxt); //J2C: finalizing the embedded instance.
  finalize_ObjectJc_F(&ythis->logMsgFileCtrlValues.base.object, _thCxt); //J2C: finalizing the embedded instance.
  finalize_ObjectJc_F(&ythis->logMsgFileGC.base.object, _thCxt); //J2C: finalizing the embedded instance.
  CLEAR_REFJc(ythis->way1Sensor);
  CLEAR_REFJc(ythis->way2Sensor);
  CLEAR_REFJc(ythis->way1Actuator);
  CLEAR_REFJc(ythis->way2Actuator);
  CLEAR_REFJc(ythis->testEnvJ2c);
  finalize_ObjectJc_F(&ythis->pidCtrl1.base.object, _thCxt); //J2C: finalizing the embedded instance.
  CLEAR_REFJc(ythis->pidCtrl2);
  finalize_ObjectJc_F(&ythis->targetReader.base.object, _thCxt); //J2C: finalizing the embedded instance.
  CLEAR_REFJc(ythis->testifc);
  CLEAR_REFJc(ythis->testDynamicReference);
  finalize_ObjectJc_F(&ythis->oamVariables.base.object, _thCxt); //J2C: finalizing the embedded instance.
  finalize_ObjectJc_F(&ythis->wayCtrlThread.base.object, _thCxt); //J2C: finalizing the embedded instance.
  finalize_ObjectJc_F(&ythis->base.object, _thCxt); //J2C: finalizing the superclass.
  STACKTRC_LEAVE;
}




/**J2C: Reflections and Method-table *************************************************/
const MtblDef_MainController mtblMainController = {
{ { sign_Mtbl_MainController//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , clone_ObjectJc_F //clone
  , equals_ObjectJc_F //equals
  , finalize_MainController_F //finalize
  , hashCode_ObjectJc_F //hashCode
  , toString_ObjectJc_F //toString
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_ObjectJc;
 static struct superClasses_MainController_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_MainController_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ObjectJc, OFFSET_Mtbl(Mtbl_MainController, ObjectJc) }
   }
 };

extern struct ClassJc_t const reflection_MainController_s;
extern struct ClassJc_t const reflection_CtrlBase_s;
extern struct ClassJc_t const reflection_DispatcherThread_MsgDispatcher_MSG_s;
extern struct ClassJc_t const reflection_InnerTest_OnlyTest_Target_SetValueGenerator_s;
extern struct ClassJc_t const reflection_LogMessageFW_i;
extern struct ClassJc_t const reflection_LogMessageFile_MSG_s;
extern struct ClassJc_t const reflection_MainController_s;
extern struct ClassJc_t const reflection_MsgDispatcher_MSG_s;
extern struct ClassJc_t const reflection_OamVariables_s;
extern struct ClassJc_t const reflection_PID_controller_s;
extern struct ClassJc_t const reflection_ReadTargetFromText_s;
extern struct ClassJc_t const reflection_SetValueGenerator_ifc_s;
extern struct ClassJc_t const reflection_TestClass_s;
extern struct ClassJc_t const reflection_Testifc_s;
extern struct ClassJc_t const reflection_WaitThreadOrganizer_s;
extern struct ClassJc_t const reflection_WayActuator_s;
extern struct ClassJc_t const reflection_WayCtrlThread_MainController_s;
extern struct ClassJc_t const reflection_WaySensor_s;
const struct Reflection_Fields_MainController_s_t
{ ObjectArrayJc head; FieldJc data[26];
} reflection_Fields_MainController_s =
{ CONST_ObjectArrayJc(FieldJc, 26, OBJTYPE_FieldJc, null, &reflection_Fields_MainController_s)
, {
     { "msg"
    , 0 //nrofArrayElements
    , &reflection_LogMessageFW_i
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->msg) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "waitCycleOrganizer"
    , 0 //nrofArrayElements
    , &reflection_WaitThreadOrganizer_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->waitCycleOrganizer) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "msgDispatcher"
    , 0 //nrofArrayElements
    , &reflection_MsgDispatcher_MSG_s
    , kEmbedded_Modifier_reflectJc |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->msgDispatcher) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "msgDispatcherThread"
    , 0 //nrofArrayElements
    , &reflection_DispatcherThread_MsgDispatcher_MSG_s
    , kReference_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->msgDispatcherThread) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "logMsgFileCtrlValues"
    , 0 //nrofArrayElements
    , &reflection_LogMessageFile_MSG_s
    , kEmbedded_Modifier_reflectJc |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->logMsgFileCtrlValues) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "logMsgFileGC"
    , 0 //nrofArrayElements
    , &reflection_LogMessageFile_MSG_s
    , kEmbedded_Modifier_reflectJc |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->logMsgFileGC) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "way1Sensor"
    , 0 //nrofArrayElements
    , &reflection_WaySensor_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->way1Sensor) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "way2Sensor"
    , 0 //nrofArrayElements
    , &reflection_WaySensor_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->way2Sensor) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "way1Actuator"
    , 0 //nrofArrayElements
    , &reflection_WayActuator_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->way1Actuator) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "way2Actuator"
    , 0 //nrofArrayElements
    , &reflection_WayActuator_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->way2Actuator) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "wWay"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->wWay) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "dWay"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->dWay) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "dWay1"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc |kObjectArrayJc_Modifier_reflectJc |kReferencedContainer_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->dWay1) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "addWay"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->addWay) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "mySetValueGenerator"
    , 0 //nrofArrayElements
    , &reflection_SetValueGenerator_ifc_s
    , kReference_Modifier_reflectJc |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->mySetValueGenerator) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "testEnvJ2c"
    , 0 //nrofArrayElements
    , &reflection_InnerTest_OnlyTest_Target_SetValueGenerator_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->testEnvJ2c) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "yOut"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->yOut) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "yOut2"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc |kObjectArrayJc_Modifier_reflectJc |kReferencedContainer_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->yOut2) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "pidCtrl1"
    , 0 //nrofArrayElements
    , &reflection_PID_controller_s
    , kEmbedded_Modifier_reflectJc |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->pidCtrl1) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "pidCtrl2"
    , 0 //nrofArrayElements
    , &reflection_CtrlBase_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->pidCtrl2) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "targetReader"
    , 0 //nrofArrayElements
    , &reflection_ReadTargetFromText_s
    , kEmbedded_Modifier_reflectJc |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->targetReader) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "testifc"
    , 0 //nrofArrayElements
    , &reflection_Testifc_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->testifc) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "testDynamicReference"
    , 0 //nrofArrayElements
    , &reflection_TestClass_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->testDynamicReference) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "oamVariables"
    , 0 //nrofArrayElements
    , &reflection_OamVariables_s
    , kEmbedded_Modifier_reflectJc |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->oamVariables) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "wayCtrlThread"
    , 0 //nrofArrayElements
    , &reflection_WayCtrlThread_MainController_s
    , kEmbedded_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((MainController_s*)(0x1000))->wayCtrlThread) - (int32)(MainController_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_MainController_s
    }
   , { "singleton"
    , 0 //nrofArrayElements
    , &reflection_MainController_s
    , kReference_Modifier_reflectJc |mObjectJc_Modifier_reflectJc |mSTATIC_Modifier_reflectJc //bitModifiers
    , 0 //compiler problem, not a constant,TODO: (int16)(&singleton_MainController) //lo part of memory address of static member
    , 0 //compiler problem, not a constant,TODO: (int16)((int32)(&singleton_MainController)>>16) //hi part of memory address of static member instead offsetToObjectifcBase, TRICKY because compatibilty.
    , &reflection_MainController_s
    }
} };
const ClassJc reflection_MainController_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "MainController_s"
,  0 //position of ObjectJc
, sizeof(MainController_s)
, (FieldJcArray const*)&reflection_Fields_MainController_s
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_MainController_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblMainController.mtbl.head
};


const char sign_Mtbl_WayCtrlThread_MainController[] = "WayCtrlThread_MainController"; //to mark method tables of all implementations

typedef struct MtblDef_WayCtrlThread_MainController_t { Mtbl_WayCtrlThread_MainController mtbl; MtblHeadJc end; } MtblDef_WayCtrlThread_MainController;
 extern MtblDef_WayCtrlThread_MainController const mtblWayCtrlThread_MainController;

/*Constructor */
struct WayCtrlThread_MainController_t* ctorO_WayCtrlThread_MainController(struct MainController_t* outer, ObjectJc* othis, StringJc sName, ThCxt* _thCxt)
{ WayCtrlThread_MainController_s* ythis = (WayCtrlThread_MainController_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_WayCtrlThread_MainController");
  checkConsistence_ObjectJc(othis, sizeof(WayCtrlThread_MainController_s), null, _thCxt);  
  //J2C:super Constructor
  ctorO_s_ThreadJc(/*static*/othis, sName, _thCxt);
  setReflection_ObjectJc(othis, &reflection_WayCtrlThread_MainController_s, sizeof(WayCtrlThread_MainController_s));  
  ythis->outer = outer;
  //j2c: Initialize all class variables:
  {
  }
  { 
    
    
  }
  STACKTRC_LEAVE;
  return ythis;
}



/**It is the main loop of the fast controller thread.*/
void run_WayCtrlThread_MainController(ObjectJc* ithis, ThCxt* _thCxt)
{ WayCtrlThread_MainController_s* ythis = (WayCtrlThread_MainController_s*)ithis;
  
  STACKTRC_TENTRY("run_WayCtrlThread_MainController");
  
  { 
    WaitThreadOrganizerMTB waitCycleOrganizer1;   /*Internal variable to hold the reference to the interface,*/
    WaySensorMTB way1Sensor;   /*same, dynamic call: */
    WaySensorMTB way2Sensor;   /*same, dynamic call: */
    SetValueGenerator_ifcMTB mySetValueGenerator;   /*same, dynamic call: */
    WayActuatorMTB way1Actuator;   /*same, dynamic call: */
    WayActuatorMTB way2Actuator;   /*same, dynamic call: */
    
    
    SETMTBJc(waitCycleOrganizer1, REFJc(ythis->outer->waitCycleOrganizer), WaitThreadOrganizer);
    SETMTBJc(way1Sensor, REFJc(ythis->outer->way1Sensor), WaySensor);
    SETMTBJc(way2Sensor, REFJc(ythis->outer->way2Sensor), WaySensor);
    SETMTBJc(mySetValueGenerator, ythis->outer->mySetValueGenerator, SetValueGenerator_ifc);
    SETMTBJc(way1Actuator, REFJc(ythis->outer->way1Actuator), WayActuator);
    SETMTBJc(way2Actuator, REFJc(ythis->outer->way2Actuator), WayActuator);
    /**unterminated loop as long as the controller runs. */
    
    while(true)
      { 
        int32 xWay;   /*reads the inputs from Hardware, it is in units 1 micrometer. */
        bool bFirstExample = false; 
        int32 wWayu = 100;   /*wWay in microMeter, the wWay is in 100um-step */
        
        
        /**Wait until cycle, it is a wait/notify from interrupt*/
        waitCycleOrganizer1.mtbl->waitCycle(&(( (waitCycleOrganizer1.ref))->base.object), _thCxt);//step();
        
        xWay = way1Sensor.mtbl->getWay(&(( (way1Sensor.ref))->base.object), _thCxt);
        ythis->outer->oamVariables.way = xWay;
        bFirstExample = false;
        if(bFirstExample) 
        { 
          
          if(ythis->outer->wWay >= 20000) 
          { 
            
            /*The way is greater the maximum. */
            ythis->outer->addWay = -50;
            setIntg_PID_controller_F(& (ythis->outer->pidCtrl1), (int16)-ythis->outer->yOut, _thCxt);
          }
          else if(ythis->outer->wWay <= 10000) 
          { 
            
            ythis->outer->addWay = 50;
            setIntg_PID_controller_F(& (ythis->outer->pidCtrl1), (int16)-ythis->outer->yOut, _thCxt);
          }
          ythis->outer->wWay += ythis->outer->addWay;
          if(ythis->outer->wWay >= 20000) ythis->outer->wWay = 1;//test Java2C only!
          
        }
        else 
        { 
          
          /*The next set-value for the way is got from the valueGenerator.*/
          ythis->outer->wWay = mySetValueGenerator.mtbl->step(&(( (mySetValueGenerator.ref))->base.object), _thCxt);
        }
        wWayu = 100 * (int32)ythis->outer->wWay;
        /*If the difference is outside a capturing range, the controller is off*/
        if(xWay > wWayu + 30000) 
        { 
          
          /*The way is out of range, move down.*/
          ythis->outer->yOut = -20000;
          ythis->outer->dWay = 30000;//for OaM
          
          setIntg_PID_controller_F(& (ythis->outer->pidCtrl1), ythis->outer->yOut, _thCxt);
        }
        else if(xWay < wWayu - 30000) 
        { 
          
          /*The way is out of range, move up. */
          ythis->outer->yOut = 20000;
          ythis->outer->dWay = -30000;//for OaM
          
          setIntg_PID_controller_F(& (ythis->outer->pidCtrl1), ythis->outer->yOut, _thCxt);
        }
        else 
        { 
          
          /**difference of way in units 1 Micrometer, range should be -32..32 mm. */
          ythis->outer->dWay = (int16)(wWayu - xWay);
          /*call of PID-control. */
          ythis->outer->yOut = calculate_PID_controller_F(& (ythis->outer->pidCtrl1), ythis->outer->dWay, _thCxt);//dWay1[0] = (short)(-dWay);  //Input for PID
          
          /*The yOut have an output range from -16768 to 16767, limit the output value: */
          if(ythis->outer->yOut > 19999) 
          { 
            
            ythis->outer->yOut = 19999;//pidCtrl1.setIntg(yOut);
            
          }
          else if(ythis->outer->yOut < -19999) 
          { 
            
            ythis->outer->yOut = -19999;//next statement commented, see above.
            
          }
        }
        way1Actuator.mtbl->setMotorVoltage(&(( (way1Actuator.ref))->base.object), (int16)(ythis->outer->yOut >> 1), _thCxt);
        ythis->outer->oamVariables.dway = ythis->outer->dWay;
        ythis->outer->oamVariables.output = ythis->outer->yOut;
      }
  }
  STACKTRC_LEAVE;
}



/**J2C: Reflections and Method-table *************************************************/
const MtblDef_WayCtrlThread_MainController mtblWayCtrlThread_MainController = {
{ { sign_Mtbl_WayCtrlThread_MainController//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_ThreadJc//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , clone_ObjectJc_F //clone
    , equals_ObjectJc_F //equals
    , finalize_ObjectJc_F //finalize
    , hashCode_ObjectJc_F //hashCode
    , toString_ObjectJc_F //toString
    }
    /**J2C: Mtbl-interfaces of WayCtrlThread_MainController: */
  , { { sign_Mtbl_RunnableJc//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((1 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , run_WayCtrlThread_MainController //run
    , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
        , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
        }
      , clone_ObjectJc_F //clone
      , equals_ObjectJc_F //equals
      , finalize_ObjectJc_F //finalize
      , hashCode_ObjectJc_F //hashCode
      , toString_ObjectJc_F //toString
      }
    }
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_ThreadJc_s;
 static struct superClasses_WayCtrlThread_MainController_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_WayCtrlThread_MainController_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ThreadJc_s, OFFSET_Mtbl(Mtbl_WayCtrlThread_MainController, ThreadJc) }
   }
 };

const ClassJc reflection_WayCtrlThread_MainController_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "WayCtrlThread_Main_troller_s"
,  0 //position of ObjectJc
, sizeof(WayCtrlThread_MainController_s)
, null //attributes and associations
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_WayCtrlThread_MainController_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblWayCtrlThread_MainController.mtbl.head
};
