/**************************************************************************
 * This file is generated by Java2C
 **copyright***************************************************************
 *************************************************************************/
#include "PosCtrl/OamVariables.h"
#include <string.h>  //because using memset()
#include <Jc/ReflectionJc.h>   //Reflection concept 
#include <Fwc/fw_Exception.h>  //basic stacktrace concept

/**This class contains some variables, which are sent to a visualization app,
an "Operation and Monitoring" app (OaM).

@author Hartmut Schorrig

*/


const char sign_Mtbl_OamVariables[] = "OamVariables"; //to mark method tables of all implementations

typedef struct MtblDef_OamVariables_t { Mtbl_OamVariables mtbl; MtblHeadJc end; } MtblDef_OamVariables;
 extern MtblDef_OamVariables const mtblOamVariables;

/*Constructor *//**J2C: autogenerated as default constructor. */
struct OamVariables_t* ctorO_OamVariables(ObjectJc* othis, ThCxt* _thCxt)
{ OamVariables_s* ythis = (OamVariables_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_OamVariables");
  checkConsistence_ObjectJc(othis, sizeof(OamVariables_s), null, _thCxt);  
  setReflection_ObjectJc(othis, &reflection_OamVariables_s, sizeof(OamVariables_s));  
  //j2c: Initialize all class variables:
  {
  }/*J2C:No body for constructor*/

  STACKTRC_LEAVE;
  return ythis;
}




/**J2C: Reflections and Method-table *************************************************/
const MtblDef_OamVariables mtblOamVariables = {
{ { sign_Mtbl_OamVariables//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , clone_ObjectJc_F //clone
  , equals_ObjectJc_F //equals
  , finalize_ObjectJc_F //finalize
  , hashCode_ObjectJc_F //hashCode
  , toString_ObjectJc_F //toString
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_ObjectJc;
 static struct superClasses_OamVariables_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_OamVariables_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ObjectJc, OFFSET_Mtbl(Mtbl_OamVariables, ObjectJc) }
   }
 };

extern struct ClassJc_t const reflection_OamVariables_s;
const struct Reflection_Fields_OamVariables_s_t
{ ObjectArrayJc head; FieldJc data[8];
} reflection_Fields_OamVariables_s =
{ CONST_ObjectArrayJc(FieldJc, 8, OBJTYPE_FieldJc, null, &reflection_Fields_OamVariables_s)
, {
     { "way"
    , 0 //nrofArrayElements
    , REFLECTION_int32
    , 4 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((OamVariables_s*)(0x1000))->way) - (int32)(OamVariables_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_OamVariables_s
    }
   , { "wway"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((OamVariables_s*)(0x1000))->wway) - (int32)(OamVariables_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_OamVariables_s
    }
   , { "targetWay"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((OamVariables_s*)(0x1000))->targetWay) - (int32)(OamVariables_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_OamVariables_s
    }
   , { "dway"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((OamVariables_s*)(0x1000))->dway) - (int32)(OamVariables_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_OamVariables_s
    }
   , { "output"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((OamVariables_s*)(0x1000))->output) - (int32)(OamVariables_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_OamVariables_s
    }
   , { "stateSetValueGen"
    , 0 //nrofArrayElements
    , REFLECTION_int16
    , 2 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((OamVariables_s*)(0x1000))->stateSetValueGen) - (int32)(OamVariables_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_OamVariables_s
    }
   , { "ctController"
    , 0 //nrofArrayElements
    , REFLECTION_int8
    , 1 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((OamVariables_s*)(0x1000))->ctController) - (int32)(OamVariables_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_OamVariables_s
    }
   , { "ctSetValue"
    , 0 //nrofArrayElements
    , REFLECTION_int8
    , 1 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((OamVariables_s*)(0x1000))->ctSetValue) - (int32)(OamVariables_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_OamVariables_s
    }
} };
const ClassJc reflection_OamVariables_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "OamVariables_s"
,  0 //position of ObjectJc
, sizeof(OamVariables_s)
, (FieldJcArray const*)&reflection_Fields_OamVariables_s
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_OamVariables_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblOamVariables.mtbl.head
};


const char sign_Mtbl_OamVariablesByteAccess_OamVariables[] = "OamVariablesByteAccess_OamVariables"; //to mark method tables of all implementations

typedef struct MtblDef_OamVariablesByteAccess_OamVariables_t { Mtbl_OamVariablesByteAccess_OamVariables mtbl; MtblHeadJc end; } MtblDef_OamVariablesByteAccess_OamVariables;
 extern MtblDef_OamVariablesByteAccess_OamVariables const mtblOamVariablesByteAccess_OamVariables;

/*Constructor *//**J2C: autogenerated as default constructor. */
struct OamVariablesByteAccess_OamVariables_t* ctorO_OamVariablesByteAccess_OamVariables(ObjectJc* othis, ThCxt* _thCxt)
{ OamVariablesByteAccess_OamVariables_s* ythis = (OamVariablesByteAccess_OamVariables_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_OamVariablesByteAccess_OamVariables");
  checkConsistence_ObjectJc(othis, sizeof(OamVariablesByteAccess_OamVariables_s), null, _thCxt);  
  //J2C:super Constructor
  ctorO_ByteDataAccessJc(/*static*/othis, _thCxt);
  setReflection_ObjectJc(othis, &reflection_OamVariablesByteAccess_OamVariables_s, sizeof(OamVariablesByteAccess_OamVariables_s));  
  //j2c: Initialize all class variables:
  {
  }/*J2C:No body for constructor*/

  STACKTRC_LEAVE;
  return ythis;
}


void specifyEmptyDefaultData_OamVariablesByteAccess_OamVariables_F(ByteDataAccessJc_s* ithis, ThCxt* _thCxt)
{ OamVariablesByteAccess_OamVariables_s* ythis = (OamVariablesByteAccess_OamVariables_s*)ithis;
  
  STACKTRC_TENTRY("specifyEmptyDefaultData_OamVariablesByteAccess_OamVariables_F");
  
  { //: TODO Auto-generated method stub
    
    
    
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
void specifyEmptyDefaultData_OamVariablesByteAccess_OamVariables(ByteDataAccessJc_s* ithis, ThCxt* _thCxt)
{ Mtbl_ByteDataAccessJc const* mtbl = (Mtbl_ByteDataAccessJc const*)getMtbl_ObjectJc(&ithis->base.object, sign_Mtbl_ByteDataAccessJc);
  mtbl->specifyEmptyDefaultData((ByteDataAccessJc_s*)ithis, _thCxt);
}

int32 specifyLengthElement_OamVariablesByteAccess_OamVariables_F(ByteDataAccessJc_s* ithis, ThCxt* _thCxt)
{ OamVariablesByteAccess_OamVariables_s* ythis = (OamVariablesByteAccess_OamVariables_s*)ithis;
  
  STACKTRC_TENTRY("specifyLengthElement_OamVariablesByteAccess_OamVariables_F");
  
  { 
    
    { STACKTRC_LEAVE;
      return sizeofHead_OamVariablesByteAccess_OamVariables;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
int32 specifyLengthElement_OamVariablesByteAccess_OamVariables(ByteDataAccessJc_s* ithis, ThCxt* _thCxt)
{ Mtbl_ByteDataAccessJc const* mtbl = (Mtbl_ByteDataAccessJc const*)getMtbl_ObjectJc(&ithis->base.object, sign_Mtbl_ByteDataAccessJc);
  return mtbl->specifyLengthElement((ByteDataAccessJc_s*)ithis, _thCxt);
}

int32 specifyLengthElementHead_OamVariablesByteAccess_OamVariables_F(ByteDataAccessJc_s* ithis, ThCxt* _thCxt)
{ OamVariablesByteAccess_OamVariables_s* ythis = (OamVariablesByteAccess_OamVariables_s*)ithis;
  
  STACKTRC_TENTRY("specifyLengthElementHead_OamVariablesByteAccess_OamVariables_F");
  
  { 
    
    { STACKTRC_LEAVE;
      return sizeofHead_OamVariablesByteAccess_OamVariables;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
int32 specifyLengthElementHead_OamVariablesByteAccess_OamVariables(ByteDataAccessJc_s* ithis, ThCxt* _thCxt)
{ Mtbl_ByteDataAccessJc const* mtbl = (Mtbl_ByteDataAccessJc const*)getMtbl_ObjectJc(&ithis->base.object, sign_Mtbl_ByteDataAccessJc);
  return mtbl->specifyLengthElementHead((ByteDataAccessJc_s*)ithis, _thCxt);
}

void addToAndSetBinData_OamVariablesByteAccess_OamVariables_F(OamVariablesByteAccess_OamVariables_s* ythis, struct ByteDataAccessJc_t* parent, struct OamVariables_t* data, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("addToAndSetBinData_OamVariablesByteAccess_OamVariables_F");
  
  { 
    
    addChild_ByteDataAccessJc(parent, & ((* (ythis)).base.super), _thCxt);
    setInt32_ii_ByteDataAccessJc(& ((* (ythis)).base.super), k_way_OamVariablesByteAccess_OamVariables, data->way, _thCxt);
    setInt16_ii_ByteDataAccessJc(& ((* (ythis)).base.super), k_wway_OamVariablesByteAccess_OamVariables, data->wway, _thCxt);
    setInt16_ii_ByteDataAccessJc(& ((* (ythis)).base.super), k_targetWay_OamVariablesByteAccess_OamVariables, data->targetWay, _thCxt);
    setInt16_ii_ByteDataAccessJc(& ((* (ythis)).base.super), k_dway_OamVariablesByteAccess_OamVariables, data->dway, _thCxt);
    setInt16_ii_ByteDataAccessJc(& ((* (ythis)).base.super), k_output_OamVariablesByteAccess_OamVariables, data->output, _thCxt);
    setInt16_ii_ByteDataAccessJc(& ((* (ythis)).base.super), k_stateSetValueGen_OamVariablesByteAccess_OamVariables, data->stateSetValueGen, _thCxt);
    setInt8_ii_ByteDataAccessJc(& ((* (ythis)).base.super), k_ctController_OamVariablesByteAccess_OamVariables, data->ctController, _thCxt);
    setInt8_ii_ByteDataAccessJc(& ((* (ythis)).base.super), k_ctSetValue_OamVariablesByteAccess_OamVariables, data->ctSetValue, _thCxt);
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
void addToAndSetBinData_OamVariablesByteAccess_OamVariables(OamVariablesByteAccess_OamVariables_s* ythis, struct ByteDataAccessJc_t* parent, struct OamVariables_t* data, ThCxt* _thCxt)
{ Mtbl_OamVariablesByteAccess_OamVariables const* mtbl = (Mtbl_OamVariablesByteAccess_OamVariables const*)getMtbl_ObjectJc(&ythis->base.object, sign_Mtbl_OamVariablesByteAccess_OamVariables);
  mtbl->addToAndSetBinData(ythis, parent, data, _thCxt);
}

void addToAndGetBinData_OamVariablesByteAccess_OamVariables_F(OamVariablesByteAccess_OamVariables_s* ythis, struct ByteDataAccessJc_t* parent, struct OamVariables_t* data, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("addToAndGetBinData_OamVariablesByteAccess_OamVariables_F");
  
  { 
    
    addChild_ByteDataAccessJc(parent, & ((* (ythis)).base.super), _thCxt);
    data->way = getInt32_i_ByteDataAccessJc(& ((* (ythis)).base.super), k_way_OamVariablesByteAccess_OamVariables, _thCxt);
    data->wway = getInt16_i_ByteDataAccessJc(& ((* (ythis)).base.super), k_wway_OamVariablesByteAccess_OamVariables, _thCxt);
    data->targetWay = getInt16_i_ByteDataAccessJc(& ((* (ythis)).base.super), k_targetWay_OamVariablesByteAccess_OamVariables, _thCxt);
    data->dway = getInt16_i_ByteDataAccessJc(& ((* (ythis)).base.super), k_dway_OamVariablesByteAccess_OamVariables, _thCxt);
    data->output = getInt16_i_ByteDataAccessJc(& ((* (ythis)).base.super), k_output_OamVariablesByteAccess_OamVariables, _thCxt);
    data->stateSetValueGen = getInt16_i_ByteDataAccessJc(& ((* (ythis)).base.super), k_stateSetValueGen_OamVariablesByteAccess_OamVariables, _thCxt);
    data->ctController = getInt8_i_ByteDataAccessJc(& ((* (ythis)).base.super), k_ctController_OamVariablesByteAccess_OamVariables, _thCxt);
    data->ctSetValue = getInt8_i_ByteDataAccessJc(& ((* (ythis)).base.super), k_ctSetValue_OamVariablesByteAccess_OamVariables, _thCxt);
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
void addToAndGetBinData_OamVariablesByteAccess_OamVariables(OamVariablesByteAccess_OamVariables_s* ythis, struct ByteDataAccessJc_t* parent, struct OamVariables_t* data, ThCxt* _thCxt)
{ Mtbl_OamVariablesByteAccess_OamVariables const* mtbl = (Mtbl_OamVariablesByteAccess_OamVariables const*)getMtbl_ObjectJc(&ythis->base.object, sign_Mtbl_OamVariablesByteAccess_OamVariables);
  mtbl->addToAndGetBinData(ythis, parent, data, _thCxt);
}



/**J2C: Reflections and Method-table *************************************************/
const MtblDef_OamVariablesByteAccess_OamVariables mtblOamVariablesByteAccess_OamVariables = {
{ { sign_Mtbl_OamVariablesByteAccess_OamVariables//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((2 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, addToAndSetBinData_OamVariablesByteAccess_OamVariables_F //addToAndSetBinData
, addToAndGetBinData_OamVariablesByteAccess_OamVariables_F //addToAndGetBinData
, { { sign_Mtbl_ByteDataAccessJc//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((14 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , specifyEmptyDefaultData_OamVariablesByteAccess_OamVariables_F //specifyEmptyDefaultData
  , specifyLengthElementHead_OamVariablesByteAccess_OamVariables_F //specifyLengthElementHead
  , specifyLengthElement_OamVariablesByteAccess_OamVariables_F //specifyLengthElement
  , specifyLengthCurrentChildElement_ByteDataAccessJc_F //specifyLengthCurrentChildElement
  , assignData_iYi_ByteDataAccessJc_F //assignData_iYi
  , assignData_iYii_ByteDataAccessJc_F //assignData_iYii
  , assignDataToFixChilds_ByteDataAccessJc_F //assignDataToFixChilds
  , notifyAddChild_ByteDataAccessJc_F //notifyAddChild
  , getString_ByteDataAccessJc_F //getString
  , setString_ByteDataAccessJc_F //setString
  , setBigEndian_ByteDataAccessJc_F //setBigEndian
  , getUint16_iii_ByteDataAccessJc_F //getUint16_iii
  , getUint8_iii_ByteDataAccessJc_F //getUint8_iii
  , getFloat_iii_ByteDataAccessJc_F //getFloat_iii
  , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , clone_ObjectJc_F //clone
    , equals_ObjectJc_F //equals
    , finalize_ByteDataAccessJc_F //finalize
    , hashCode_ObjectJc_F //hashCode
    , toString_ObjectJc_F //toString
    }
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_ByteDataAccessJc_s;
 static struct superClasses_OamVariablesByteAccess_OamVariables_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_OamVariablesByteAccess_OamVariables_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ByteDataAccessJc_s, OFFSET_Mtbl(Mtbl_OamVariablesByteAccess_OamVariables, ByteDataAccessJc) }
   }
 };

const ClassJc reflection_OamVariablesByteAccess_OamVariables_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "OamVariablesByteAc_riables_s"
,  0 //position of ObjectJc
, sizeof(OamVariablesByteAccess_OamVariables_s)
, null //attributes and associations
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_OamVariablesByteAccess_OamVariables_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblOamVariablesByteAccess_OamVariables.mtbl.head
};
