/**************************************************************************
 * This file is generated by Java2C
 **copyright***************************************************************
 *************************************************************************/
#include "PosCtrl/SetValueGenerator_ifc.h"
#include <string.h>  //because using memset()
#include <Jc/ReflectionJc.h>   //Reflection concept 
#include <Fwc/fw_Exception.h>  //basic stacktrace concept


const char sign_Mtbl_SetValueGenerator_ifc[] = "SetValueGenerator_ifc"; //to mark method tables of all implementations


/**stores a next target point*/
/*J2C: dynamic call variant of the override-able method: */
bool setTarget_SetValueGenerator_ifc(ObjectJc* ithis, int16 targetValue, ThCxt* _thCxt)
{ Mtbl_SetValueGenerator_ifc const* mtbl = (Mtbl_SetValueGenerator_ifc const*)getMtbl_ObjectJc(ithis, sign_Mtbl_SetValueGenerator_ifc);
  return mtbl->setTarget(ithis, targetValue, _thCxt);
}


/**generates the next reference value.*/
/*J2C: dynamic call variant of the override-able method: */
int16 step_SetValueGenerator_ifc(ObjectJc* ithis, ThCxt* _thCxt)
{ Mtbl_SetValueGenerator_ifc const* mtbl = (Mtbl_SetValueGenerator_ifc const*)getMtbl_ObjectJc(ithis, sign_Mtbl_SetValueGenerator_ifc);
  return mtbl->step(ithis, _thCxt);
}

 extern struct ClassJc_t const reflection_ObjectJc;
 static struct superClasses_SetValueGenerator_ifc_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_SetValueGenerator_ifc_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ObjectJc, 0 /*J2C: no Mtbl*/ }
   }
 };

const ClassJc reflection_SetValueGenerator_ifc_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "SetValueGenerator_ifc_s"
,  0 //position of ObjectJc
, sizeof(SetValueGenerator_ifc_s)
, null //attributes and associations
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_SetValueGenerator_ifc_s //superclass
, null //interfaces
, 0    //modifiers
};
