/**************************************************************************
 * This file is generated by Java2C
 **copyright***************************************************************
 *************************************************************************/
#include "PosCtrl/WayActuator.h"
#include <string.h>  //because using memset()
#include <Jc/ReflectionJc.h>   //Reflection concept 
#include <Fwc/fw_Exception.h>  //basic stacktrace concept

/**This interface is the access to Hardware.
In the target platform it is a routine directly programmed in C.
The interface reference helps to select the instance of Actuator.
In C it may not be implemented with a java-like interface concept, but more simple.
*/


const char sign_Mtbl_WayActuator[] = "WayActuator"; //to mark method tables of all implementations


/**Sets the output to the motor*/
/*J2C: dynamic call variant of the override-able method: */
void setMotorVoltage_WayActuator(ObjectJc* ithis, int16 value, ThCxt* _thCxt)
{ Mtbl_WayActuator const* mtbl = (Mtbl_WayActuator const*)getMtbl_ObjectJc(ithis, sign_Mtbl_WayActuator);
  mtbl->setMotorVoltage(ithis, value, _thCxt);
}

 extern struct ClassJc_t const reflection_ObjectJc;
 static struct superClasses_WayActuator_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_WayActuator_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ObjectJc, 0 /*J2C: no Mtbl*/ }
   }
 };

const ClassJc reflection_WayActuator_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "WayActuator_s"
,  0 //position of ObjectJc
, sizeof(WayActuator_s)
, null //attributes and associations
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_WayActuator_s //superclass
, null //interfaces
, 0    //modifiers
};
