/**************************************************************************
 * This file is generated by Java2C
 **copyright***************************************************************
 *************************************************************************/
#include "PosCtrl/WayCtrlThread.h"
#include <string.h>  //because using memset()
#include <Jc/ReflectionJc.h>   //Reflection concept 
#include <Fwc/fw_Exception.h>  //basic stacktrace concept


const char sign_Mtbl_WayCtrlThread[] = "WayCtrlThread"; //to mark method tables of all implementations

typedef struct MtblDef_WayCtrlThread_t { Mtbl_WayCtrlThread mtbl; MtblHeadJc end; } MtblDef_WayCtrlThread;
 extern MtblDef_WayCtrlThread const mtblWayCtrlThread;

/*Constructor */
struct WayCtrlThread_t* ctorO_WayCtrlThread(ObjectJc* othis, struct LogMessageFW_t* log, ThCxt* _thCxt)
{ WayCtrlThread_s* ythis = (WayCtrlThread_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_WayCtrlThread");
  checkConsistence_ObjectJc(othis, sizeof(WayCtrlThread_s), null, _thCxt);  
  setReflection_ObjectJc(othis, &reflection_WayCtrlThread_s, sizeof(WayCtrlThread_s));  
  //j2c: Initialize all class variables:
  {
  }
  { 
    
    SETREFJc(ythis->log, log, LogMessageFW_i);
  }
  STACKTRC_LEAVE;
  return ythis;
}


void run_WayCtrlThread_F(ObjectJc* ithis, ThCxt* _thCxt)
{ WayCtrlThread_s* ythis = (WayCtrlThread_s*)ithis;
  
  STACKTRC_TENTRY("run_WayCtrlThread_F");
  
  { 
    
    
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
void run_WayCtrlThread(ObjectJc* ithis, ThCxt* _thCxt)
{ Mtbl_RunnableJc const* mtbl = (Mtbl_RunnableJc const*)getMtbl_ObjectJc(ithis, sign_Mtbl_RunnableJc);
  mtbl->run(ithis, _thCxt);
}


void finalize_WayCtrlThread_F(ObjectJc* othis, ThCxt* _thCxt)
{ WayCtrlThread_s* ythis = (WayCtrlThread_s*)othis;  //upcasting to the real class.
 STACKTRC_TENTRY("finalize_WayCtrlThread_F");
  CLEAR_REFJc(ythis->log);
  finalize_ObjectJc_F(&ythis->base.object, _thCxt); //J2C: finalizing the superclass.
  STACKTRC_LEAVE;
}




/**J2C: Reflections and Method-table *************************************************/
const MtblDef_WayCtrlThread mtblWayCtrlThread = {
{ { sign_Mtbl_WayCtrlThread//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , clone_ObjectJc_F //clone
  , equals_ObjectJc_F //equals
  , finalize_WayCtrlThread_F //finalize
  , hashCode_ObjectJc_F //hashCode
  , toString_ObjectJc_F //toString
  }
  /**J2C: Mtbl-interfaces of WayCtrlThread: */
, { { sign_Mtbl_RunnableJc//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((1 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , run_WayCtrlThread_F //run
  , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , clone_ObjectJc_F //clone
    , equals_ObjectJc_F //equals
    , finalize_WayCtrlThread_F //finalize
    , hashCode_ObjectJc_F //hashCode
    , toString_ObjectJc_F //toString
    }
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_ObjectJc;
 static struct superClasses_WayCtrlThread_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_WayCtrlThread_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ObjectJc, OFFSET_Mtbl(Mtbl_WayCtrlThread, ObjectJc) }
   }
 };

 extern struct ClassJc_t const reflection_RunnableJc_s;
 static struct ifcClasses_WayCtrlThread_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }interfaces_WayCtrlThread_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
, { {&reflection_RunnableJc_s, OFFSET_Mtbl(Mtbl_WayCtrlThread, RunnableJc) }
  }
};

extern struct ClassJc_t const reflection_WayCtrlThread_s;
extern struct ClassJc_t const reflection_LogMessageFW_i;
const struct Reflection_Fields_WayCtrlThread_s_t
{ ObjectArrayJc head; FieldJc data[1];
} reflection_Fields_WayCtrlThread_s =
{ CONST_ObjectArrayJc(FieldJc, 1, OBJTYPE_FieldJc, null, &reflection_Fields_WayCtrlThread_s)
, {
     { "log"
    , 0 //nrofArrayElements
    , &reflection_LogMessageFW_i
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((WayCtrlThread_s*)(0x1000))->log) - (int32)(WayCtrlThread_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_WayCtrlThread_s
    }
} };
const ClassJc reflection_WayCtrlThread_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "WayCtrlThread_s"
, (int16)((int32)(&((WayCtrlThread_s*)(0x1000))->base.object) - (int32)(WayCtrlThread_s*)0x1000)
, sizeof(WayCtrlThread_s)
, (FieldJcArray const*)&reflection_Fields_WayCtrlThread_s
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_WayCtrlThread_s //superclass
, (ClassOffset_idxMtblJcARRAY*)&interfaces_WayCtrlThread_s //interfaces
, mObjectJc_Modifier_reflectJc
, &mtblWayCtrlThread.mtbl.head
};
