/**************************************************************************
 * This file is generated by Java2C
 **copyright***************************************************************
 *************************************************************************/
#ifndef __PosCtrl_WaySensor_h__
#define __PosCtrl_WaySensor_h__

#include "Jc/ObjectJc.h"        //basic concept

#include "Jc/StringJc.h"        //used often

#include "Fwc/fw_Exception.h"   //basic concept


/* J2C: includes *********************************************************/


/*@CLASS_C WaySensor @@@@@@@@@@@@@@@@@@@@@@@@*/

typedef struct WaySensor_t
{ 
  union { ObjectJc object; } base; 
} WaySensor_s;
  

#define sizeof_WaySensor_s sizeof(WaySensor_s)


/**J2c: Definitions of the enhanced reference. It's conditinally because it may be defined in a included header before. */
#ifndef WaySensorREFDEF
  #define WaySensorREFDEF
  typedef struct WaySensorREF_t { ObjectRefValuesJc refbase; struct WaySensor_t* ref; } WaySensorREF;
#endif

/**J2c: Definitions of the array forms. NOTE: The number of elements are a helper for debug, the really used number depends on the memory size! */
typedef struct WaySensor_X_t { ObjectArrayJc head; WaySensorREF data[50]; } WaySensor_X;
typedef struct WaySensor_Y_t { ObjectArrayJc head; WaySensor_s data[50]; } WaySensor_Y;

 extern struct ClassJc_t const reflection_WaySensor_s;
  


/**CONST_Type useable as initializer for embedded/stack-instances*/
#define CONST_WaySensor(OBJP) { CONST_ObjectJc(sizeof(WaySensor_s), OBJP, &reflection_WaySensor_s), 0 }

/**J2C: finalize declaration. It is called by Garbage collector and inside other finalized methods.
 * It should be called by the user if the instance is removed. */
void finalize_WaySensor_F(ObjectJc* othis, ThCxt* _thCxt);




/**gets a actual way*/
typedef int32 MT_getWay_WaySensor(ObjectJc* ithis, ThCxt* _thCxt);
/* J2C:Call of the method at this class level, executes a dynamic call of the override-able method: */
METHOD_C int32 getWay_WaySensor(ObjectJc* ithis, ThCxt* _thCxt);


/* J2C: Method table contains all dynamic linked (virtual) methods
 * of the class and all super classes and interfaces. */
 extern const char sign_Mtbl_WaySensor[]; //marker for methodTable check
typedef struct Mtbl_WaySensor_t
{ MtblHeadJc head;
  MT_getWay_WaySensor* getWay;
  Mtbl_ObjectJc ObjectJc;
} Mtbl_WaySensor;



#if defined(__CPLUSPLUSJcpp) && defined(__cplusplus)
/* J2C: The C++-class-definition. */
class WaySensor : private WaySensor_s
{ public:

  virtual int32 getWay()=0;
};

#endif /*__CPLUSPLUSJcpp*/

#endif //__PosCtrl_WaySensor_h__
