/* This file, generated by Java2C, contains all enhanced reference definitions.
 * It needs no further includes, because all user types are forward declared.
 * This file is included overall to know the requested enhanced reference types.
 * Enhanced reference types are used for all interfaces and dynamic instances.
 */
#ifndef __allReferences_h__
#define __allReferences_h__
typedef struct TestClassRef_t { ObjectRefValuesJc refbase; struct TestClass_t* ref; } TestClassREF;
typedef struct TestGarbageCollectorRef_t { ObjectRefValuesJc refbase; struct TestGarbageCollector_t* ref; } TestGarbageCollectorREF;
#endif  //__allReferences_h__