#ifndef __TestClass_h__
#define __TestClass_h__
//this file is generated by Java2C

#include "ObjectJc.h"

#include "ExceptionJc.h"

#include "allReferences.h"
typedef struct TestClass_t
{ ObjectJc object;
  int32 a;
  TestClassREF test1;  /*There is an aggregation to use it in Garbage Collection. */
  TestClassREF test2;  /*There is a second aggregation to use it in Garbage Collection, a cluster of objects will be built. */
} TestClass;
  

extern struct ClassJc_t const* clazzTestClass;
  


METHOD_C TestClass* ctorO_TestClass(ObjectJc* yObj, int32 val, struct ThreadContextJc_t* _threadContext);



void finalize_TestClass(ObjectJc* yObj, struct ThreadContextJc_t* _threadContext);
#endif //__TestClass_h__
