/**************************************************************************
 * This file is generated by Java2C
 **copyright***************************************************************
 *************************************************************************/
#include "simPc/iRequireMainController.h"
#include <string.h>  //because using memset()
#include <Jc/ReflectionJc.h>   //Reflection concept 
#include <Fwc/fw_Exception.h>  //basic stacktrace concept

/**This interface contains all requirenesses of the MainController
from the external environment. It should be implemented in the constructing class.
@author JcHartmut

*/


const char sign_Mtbl_iRequireMainController[] = "iRequireMainController"; //to mark method tables of all implementations

/*J2C: dynamic call variant of the override-able method: */
struct WaySensor_t* requireWay1Sensor_iRequireMainController(ObjectJc* ithis, ThCxt* _thCxt)
{ Mtbl_iRequireMainController const* mtbl = (Mtbl_iRequireMainController const*)getMtbl_ObjectJc(ithis, sign_Mtbl_iRequireMainController);
  return mtbl->requireWay1Sensor(ithis, _thCxt);
}

/*J2C: dynamic call variant of the override-able method: */
struct WaySensor_t* requireWay2Sensor_iRequireMainController(ObjectJc* ithis, ThCxt* _thCxt)
{ Mtbl_iRequireMainController const* mtbl = (Mtbl_iRequireMainController const*)getMtbl_ObjectJc(ithis, sign_Mtbl_iRequireMainController);
  return mtbl->requireWay2Sensor(ithis, _thCxt);
}

/*J2C: dynamic call variant of the override-able method: */
struct WayActuator_t* requireWay1Actuator_iRequireMainController(ObjectJc* ithis, ThCxt* _thCxt)
{ Mtbl_iRequireMainController const* mtbl = (Mtbl_iRequireMainController const*)getMtbl_ObjectJc(ithis, sign_Mtbl_iRequireMainController);
  return mtbl->requireWay1Actuator(ithis, _thCxt);
}

/*J2C: dynamic call variant of the override-able method: */
struct WayActuator_t* requireWay2Actuator_iRequireMainController(ObjectJc* ithis, ThCxt* _thCxt)
{ Mtbl_iRequireMainController const* mtbl = (Mtbl_iRequireMainController const*)getMtbl_ObjectJc(ithis, sign_Mtbl_iRequireMainController);
  return mtbl->requireWay2Actuator(ithis, _thCxt);
}

 extern struct ClassJc_t const reflection_ObjectJc;
 static struct superClasses_iRequireMainController_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_iRequireMainController_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ObjectJc, 0 /*J2C: no Mtbl*/ }
   }
 };

const ClassJc reflection_iRequireMainController_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "iRequireMainController_s"
,  0 //position of ObjectJc
, sizeof(iRequireMainController_s)
, null //attributes and associations
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_iRequireMainController_s //superclass
, null //interfaces
, 0    //modifiers
};
