/**************************************************************************
 * This file is generated by Java2C
 **copyright***************************************************************
 *************************************************************************/
#include "Java2cTest/ImplTest.h"
#include <string.h>  //because using memset()
#include <Jc/ReflectionJc.h>   //Reflection concept 
#include <Fwc/fw_Exception.h>  //basic stacktrace concept
#include "Jc/StringJc.h"  //embedded type in class data

/**This class is an example for implementation of some interface methods.
<br>
The superclass {@link SimpleDataStruct} is a very simple class, only contains data.
The interfaces are complex, it contains methods with same name but different parameters,
also dispersed to both interfaces. So the implementation of methods using method tables
can be demonstrated. See descriptions of the method.
<br>
Visit the translated ImplIfc_Test.c and ImplIfc_Test.h.
<br>
The struct of the class is defined in the Headerfile:
<pre class="CCode">
typedef struct ImplIfc_Test_t
{
union { ObjectJc object; ExpandableDataStruct_Test_s super;
Ifc_Test_s Ifc_Test;Ifc2_Test_s Ifc2_Test;
} base;
int32 val;
} ImplIfc_Test_s;

</pre>
The other struct is the method table, it is shown as explanation on method {@link #anotherIfcmethod(float)}.
The method table shows and represents the structure of dynamic call-able (virtual) methods
including the inheritance- and interface structure of this class. The implementation of interface
of this class in Java is transformed in C in the first place there.
*/


const char sign_Mtbl_ImplIfcTest[] = "ImplIfcTest"; //to mark method tables of all implementations

typedef struct MtblDef_ImplIfcTest_t { Mtbl_ImplIfcTest mtbl; MtblHeadJc end; } MtblDef_ImplIfcTest;
 extern MtblDef_ImplIfcTest const mtblImplIfcTest;

/*Constructor */
struct ImplIfcTest_t* ctorO_ImplIfcTest(ObjectJc* othis, int32 val, ThCxt* _thCxt)
{ ImplIfcTest_s* ythis = (ImplIfcTest_s*)othis;  //upcasting to the real class.
  Mtbl_ImplIfcTest const* mtthis = &mtblImplIfcTest.mtbl;
  STACKTRC_TENTRY("ctorO_ImplIfcTest");
  checkConsistence_ObjectJc(othis, sizeof(ImplIfcTest_s), null, _thCxt);  
  //J2C:super Constructor
  ctorO_SimpleClass_Test(/*static*/othis, _thCxt);
  setReflection_ObjectJc(othis, &reflection_ImplIfcTest_s, sizeof(ImplIfcTest_s));  
  //j2c: Initialize all class variables:
  {
    //J2C: constructor for embedded element-ObjectJc
      init_ObjectJc(&(ythis->data.base.object), sizeof(ythis->data), 0); 
      ctorO_AnyClass_Test(/*static*/&(ythis->data.base.object), ythis, _thCxt);
  }
  { 
    
    /**In the constructor a overridden method of a interface is used, call it dynamically. */
    ythis->val = mtthis->IfcToTest.processIfcMethod(&((& ((* (ythis)).base.IfcToTest))->base.object), val, _thCxt);
  }
  STACKTRC_LEAVE;
  return ythis;
}



/**Example for a method which is override-able and implements an interface method.*/
int32 processIfcMethod_i_ImplIfcTest_F(ObjectJc* ithis, int32 input, ThCxt* _thCxt)
{ ImplIfcTest_s* ythis = (ImplIfcTest_s*)ithis;
  
  STACKTRC_TENTRY("processIfcMethod_i_ImplIfcTest_F");
  
  { 
    
    { STACKTRC_LEAVE;
      return ythis->base.super.x1 + input + ythis->val;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
int32 processIfcMethod_i_ImplIfcTest(ObjectJc* ithis, int32 input, ThCxt* _thCxt)
{ Mtbl_IfcToTest const* mtbl = (Mtbl_IfcToTest const*)getMtbl_ObjectJc(ithis, sign_Mtbl_IfcToTest);
  return mtbl->processIfcMethod(ithis, input, _thCxt);
}


/**Example for a method which is final but implements an interface method (the same is if it*/
float processIfcMethod_f_ImplIfcTest(ObjectJc* ithis, float input, ThCxt* _thCxt)
{ ImplIfcTest_s* ythis = (ImplIfcTest_s*)ithis;
  
  STACKTRC_TENTRY("processIfcMethod_f_ImplIfcTest");
  
  { 
    
    { STACKTRC_LEAVE;
      return 3.56F * input;
    }
  }
  STACKTRC_LEAVE;
}


/**This method is declared in the interface {@link Ifc#processIfcMethod(int)} .*/
int32 anotherIfcmethod_i_ImplIfcTest(ObjectJc* ithis, int32 input, ThCxt* _thCxt)
{ ImplIfcTest_s* ythis = (ImplIfcTest_s*)ithis;
  
  STACKTRC_TENTRY("anotherIfcmethod_i_ImplIfcTest");
  
  { 
    
    { STACKTRC_LEAVE;
      return 34 + input;
    }
  }
  STACKTRC_LEAVE;
}

StringJc toString_ImplIfcTest_F(ObjectJc* ithis, ThCxt* _thCxt)
{ ImplIfcTest_s* ythis = (ImplIfcTest_s*)ithis;
  
  STACKTRC_TENTRY("toString_ImplIfcTest_F");
  
  { 
    
    { STACKTRC_LEAVE;
      return s0_StringJc("ImplIfc");
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
StringJc toString_ImplIfcTest(ObjectJc* ithis, ThCxt* _thCxt)
{ Mtbl_ObjectJc const* mtbl = (Mtbl_ObjectJc const*)getMtbl_ObjectJc(ithis, sign_Mtbl_ObjectJc);
  return mtbl->toString(ithis, _thCxt);
}


/**Example for a simple method, no implementation, no override-able.*/
int32 testImplIfc_ImplIfcTest(ImplIfcTest_s* ythis, ThCxt* _thCxt)
{ Mtbl_ImplIfcTest const* mtthis = (Mtbl_ImplIfcTest const*)getMtbl_ObjectJc(&ythis->base.object, sign_Mtbl_ImplIfcTest);
  
  STACKTRC_TENTRY("testImplIfc_ImplIfcTest");
  
  { 
    int32 a; 
    
    
    a = mtthis->IfcToTest.processIfcMethod(&((& ((* (ythis)).base.IfcToTest))->base.object), 5, _thCxt);
    a += (int32)processIfcMethod_f_ImplIfcTest(&((& ((* (ythis)).base.Ifc2_Test))->base.object), 6.28F, _thCxt);
    a += (int32)testIfc2_f_ImplIfcTest(&((& ((* (ythis)).base.Ifc2_Test))->base.object), 23.4F, _thCxt);
    a += mtthis->testOverrideAble(ythis, 3.14F, _thCxt);
    { STACKTRC_LEAVE;
      return a;
    }
  }
  STACKTRC_LEAVE;
}


/**This method implements {@link Ifc2#testIfc2(float)}. */
float testIfc2_f_ImplIfcTest(ObjectJc* ithis, float input, ThCxt* _thCxt)
{ ImplIfcTest_s* ythis = (ImplIfcTest_s*)ithis;
  
  STACKTRC_TENTRY("testIfc2_f_ImplIfcTest");
  
  { 
    
    { STACKTRC_LEAVE;
      return input / 3.14F;
    }
  }
  STACKTRC_LEAVE;
}


/**This method should demonstrate override-able methods for Java2C outside of interface-concepts.*/
int32 testOverrideAble_ImplIfcTest_F(ImplIfcTest_s* ythis, float value, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("testOverrideAble_ImplIfcTest_F");
  
  { 
    
    { STACKTRC_LEAVE;
      return (int32)value;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
int32 testOverrideAble_ImplIfcTest(ImplIfcTest_s* ythis, float value, ThCxt* _thCxt)
{ Mtbl_ImplIfcTest const* mtbl = (Mtbl_ImplIfcTest const*)getMtbl_ObjectJc(&ythis->base.object, sign_Mtbl_ImplIfcTest);
  return mtbl->testOverrideAble(ythis, value, _thCxt);
}


/**This method should demonstrate overridden methods of base classes*/
int32 testOverridden_ImplIfcTest_F(ImplIfcTest_s* ythis, float value, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("testOverridden_ImplIfcTest_F");
  
  { 
    
    { STACKTRC_LEAVE;
      return (int32)value;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
int32 testOverridden_ImplIfcTest(ImplIfcTest_s* ythis, float value, ThCxt* _thCxt)
{ Mtbl_ImplIfcTest const* mtbl = (Mtbl_ImplIfcTest const*)getMtbl_ObjectJc(&ythis->base.object, sign_Mtbl_ImplIfcTest);
  return mtbl->testOverridden(ythis, value, _thCxt);
}


/**This method demonstrates, how a concatenation of method calls works, if the method returns this itself.*/
struct ImplIfcTest_t* returnThis_ImplIfcTest(ImplIfcTest_s* ythis, int32 value, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("returnThis_ImplIfcTest");
  
  { 
    
    ythis->val = value;
    { STACKTRC_LEAVE;
      return ythis;
    }
  }
  STACKTRC_LEAVE;
}


/**This method demonstrates, how a concatenation of method calls works, if the method returns this itself.*/
struct ImplIfcTest_t* returnThisOverrideable_ImplIfcTest_F(ImplIfcTest_s* ythis, int32 value, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("returnThisOverrideable_ImplIfcTest_F");
  
  { 
    
    ythis->val = value;
    { STACKTRC_LEAVE;
      return ythis;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
struct ImplIfcTest_t* returnThisOverrideable_ImplIfcTest(ImplIfcTest_s* ythis, int32 value, ThCxt* _thCxt)
{ Mtbl_ImplIfcTest const* mtbl = (Mtbl_ImplIfcTest const*)getMtbl_ObjectJc(&ythis->base.object, sign_Mtbl_ImplIfcTest);
  return mtbl->returnThisOverrideable(ythis, value, _thCxt);
}


/**This method demonstrates, how a concatenation of method calls works, if the method returns any other reference.*/
struct AnyClass_Test_t* returnAnyInstanceOverrideable_ImplIfcTest_F(ImplIfcTest_s* ythis, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("returnAnyInstanceOverrideable_ImplIfcTest_F");
  
  { 
    
    { STACKTRC_LEAVE;
      return & (ythis->data);
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
struct AnyClass_Test_t* returnAnyInstanceOverrideable_ImplIfcTest(ImplIfcTest_s* ythis, ThCxt* _thCxt)
{ Mtbl_ImplIfcTest const* mtbl = (Mtbl_ImplIfcTest const*)getMtbl_ObjectJc(&ythis->base.object, sign_Mtbl_ImplIfcTest);
  return mtbl->returnAnyInstanceOverrideable(ythis, _thCxt);
}


/**This method demonstrates, how a concatenation of method calls works, if the method returns any other reference.*/
struct AnyClass_Test_t* returnAnyInstance_ImplIfcTest(ImplIfcTest_s* ythis, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("returnAnyInstance_ImplIfcTest");
  
  { 
    
    { STACKTRC_LEAVE;
      return & (ythis->data);
    }
  }
  STACKTRC_LEAVE;
}


/**This methods implements both methods declared in Interface {@link Ifc#anotherIfcmethod(float)}*/
float anotherIfcmethod_f_ImplIfcTest_F(ObjectJc* ithis, float input, ThCxt* _thCxt)
{ ImplIfcTest_s* ythis = (ImplIfcTest_s*)ithis;
  
  STACKTRC_TENTRY("anotherIfcmethod_f_ImplIfcTest_F");
  
  { 
    
    { STACKTRC_LEAVE;
      return 3.5F * input;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
float anotherIfcmethod_f_ImplIfcTest(ObjectJc* ithis, float input, ThCxt* _thCxt)
{ Mtbl_IfcToTest const* mtbl = (Mtbl_IfcToTest const*)getMtbl_ObjectJc(ithis, sign_Mtbl_IfcToTest);
  return mtbl->anotherIfcmethod_f(ithis, input, _thCxt);
}


void finalize_ImplIfcTest_F(ObjectJc* othis, ThCxt* _thCxt)
{ ImplIfcTest_s* ythis = (ImplIfcTest_s*)othis;  //upcasting to the real class.
 STACKTRC_TENTRY("finalize_ImplIfcTest_F");
  CLEAR_REFJc(ythis->ref);
  finalize_AnyClass_Test_F(&ythis->data.base.object, _thCxt); //J2C: finalizing the embedded instance.
  finalize_SimpleClass_Test_F(&ythis->base.object, _thCxt); //J2C: finalizing the superclass.
  STACKTRC_LEAVE;
}




/**J2C: Reflections and Method-table *************************************************/
const MtblDef_ImplIfcTest mtblImplIfcTest = {
{ { sign_Mtbl_ImplIfcTest//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((4 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, testOverrideAble_ImplIfcTest_F //testOverrideAble
, testOverridden_ImplIfcTest_F //testOverridden
, returnThisOverrideable_ImplIfcTest_F //returnThisOverrideable
, returnAnyInstanceOverrideable_ImplIfcTest_F //returnAnyInstanceOverrideable
, { { sign_Mtbl_SimpleClass_Test//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((2 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , addValue_SimpleClass_Test_F //addValue
  , getValue_SimpleClass_Test_F //getValue
  , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , clone_ObjectJc_F //clone
    , equals_ObjectJc_F //equals
    , finalize_ImplIfcTest_F //finalize
    , hashCode_ObjectJc_F //hashCode
    , toString_ImplIfcTest_F //toString
    }
  }
  /**J2C: Mtbl-interfaces of ImplIfcTest: */
, { { sign_Mtbl_IfcToTest//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((3 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , processIfcMethod_i_ImplIfcTest_F //processIfcMethod
  , anotherIfcmethod_i_ImplIfcTest //anotherIfcmethod_i
  , anotherIfcmethod_f_ImplIfcTest_F //anotherIfcmethod_f
  , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , clone_ObjectJc_F //clone
    , equals_ObjectJc_F //equals
    , finalize_ImplIfcTest_F //finalize
    , hashCode_ObjectJc_F //hashCode
    , toString_ImplIfcTest_F //toString
    }
  }
, { { sign_Mtbl_Ifc2_Test//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((3 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , processIfcMethod_f_ImplIfcTest //processIfcMethod
  , testIfc2_f_ImplIfcTest //testIfc2
  , anotherIfcmethod_f_ImplIfcTest_F //anotherIfcmethod
  , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , clone_ObjectJc_F //clone
    , equals_ObjectJc_F //equals
    , finalize_ImplIfcTest_F //finalize
    , hashCode_ObjectJc_F //hashCode
    , toString_ImplIfcTest_F //toString
    }
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_SimpleClass_Test_s;
 static struct superClasses_ImplIfcTest_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_ImplIfcTest_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_SimpleClass_Test_s, OFFSET_Mtbl(Mtbl_ImplIfcTest, SimpleClass_Test) }
   }
 };

 extern struct ClassJc_t const reflection_IfcToTest_s;
 extern struct ClassJc_t const reflection_Ifc2_Test_s;
 static struct ifcClasses_ImplIfcTest_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[2];
 }interfaces_ImplIfcTest_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
, { {&reflection_IfcToTest_s, OFFSET_Mtbl(Mtbl_ImplIfcTest, IfcToTest) }
  , {&reflection_Ifc2_Test_s, OFFSET_Mtbl(Mtbl_ImplIfcTest, Ifc2_Test) }
  }
};

extern struct ClassJc_t const reflection_ImplIfcTest_s;
extern struct ClassJc_t const reflection_AnyClass_Test_s;
extern struct ClassJc_t const reflection_IfcToTest_s;
const struct Reflection_Fields_ImplIfcTest_s_t
{ ObjectArrayJc head; FieldJc data[3];
} reflection_Fields_ImplIfcTest_s =
{ CONST_ObjectArrayJc(FieldJc, 3, OBJTYPE_FieldJc, null, &reflection_Fields_ImplIfcTest_s)
, {
     { "val"
    , 0 //nrofArrayElements
    , REFLECTION_int32
    , 4 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((ImplIfcTest_s*)(0x1000))->val) - (int32)(ImplIfcTest_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_ImplIfcTest_s
    }
   , { "ref"
    , 0 //nrofArrayElements
    , &reflection_IfcToTest_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((ImplIfcTest_s*)(0x1000))->ref) - (int32)(ImplIfcTest_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_ImplIfcTest_s
    }
   , { "data"
    , 0 //nrofArrayElements
    , &reflection_AnyClass_Test_s
    , kEmbedded_Modifier_reflectJc |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((ImplIfcTest_s*)(0x1000))->data) - (int32)(ImplIfcTest_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_ImplIfcTest_s
    }
} };
const ClassJc reflection_ImplIfcTest_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "ImplIfcTest_s"
, (int16)((int32)(&((ImplIfcTest_s*)(0x1000))->base.object) - (int32)(ImplIfcTest_s*)0x1000)
, sizeof(ImplIfcTest_s)
, (FieldJcArray const*)&reflection_Fields_ImplIfcTest_s
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_ImplIfcTest_s //superclass
, (ClassOffset_idxMtblJcARRAY*)&interfaces_ImplIfcTest_s //interfaces
, mObjectJc_Modifier_reflectJc
, &mtblImplIfcTest.mtbl.head
};
