/**************************************************************************
 * This file is generated by Java2C
 **copyright***************************************************************
 *************************************************************************/
#include "TestAnonymous_Test.h"
#include <string.h>  //because using memset()
#include <Jc/ReflectionJc.h>   //Reflection concept 
#include <Fwc/fw_Exception.h>  //basic stacktrace concept
#include "Jc/FileIoJc.h"  //reference-association: out
#include "Jc/MathJc.h"  //reference-association: MathJc_s
#include "Jc/StringJc.h"  //string concatenation
#include "Jc/SystemJc.h"  //reference-association: SystemJc


/*@CLASS_C C_refTempSimpleClass_TestAnonymous_Test @@@@@@@@@@@@@@@@@@@@@@@@*/

typedef struct C_refTempSimpleClass_TestAnonymous_Test_t
{ 
  union { ObjectJc object; SimpleClass_Test_s super;} base; 
  struct TestAnonymous_Test_t* outer;  //J2C: Reference to outer class, implicit in Java
} C_refTempSimpleClass_TestAnonymous_Test_s;
  

#define sizeof_C_refTempSimpleClass_TestAnonymous_Test_s sizeof(C_refTempSimpleClass_TestAnonymous_Test_s)


/**J2c: Definitions of the enhanced reference. It's conditinally because it may be defined in a included header before. */
#ifndef C_refTempSimpleClass_TestAnonymous_TestREFDEF
  #define C_refTempSimpleClass_TestAnonymous_TestREFDEF
  typedef struct C_refTempSimpleClass_TestAnonymous_TestREF_t { ObjectRefValuesJc refbase; struct C_refTempSimpleClass_TestAnonymous_Test_t* ref; } C_refTempSimpleClass_TestAnonymous_TestREF;
#endif

/**J2c: Definitions of the array forms. NOTE: The number of elements are a helper for debug, the really used number depends on the memory size! */
typedef struct C_refTempSimpleClass_TestAnonymous_Test_X_t { ObjectArrayJc head; C_refTempSimpleClass_TestAnonymous_TestREF data[50]; } C_refTempSimpleClass_TestAnonymous_Test_X;
typedef struct C_refTempSimpleClass_TestAnonymous_Test_Y_t { ObjectArrayJc head; C_refTempSimpleClass_TestAnonymous_Test_s data[50]; } C_refTempSimpleClass_TestAnonymous_Test_Y;

 extern struct ClassJc_t const reflection_C_refTempSimpleClass_TestAnonymous_Test_s;
  


/**CONST_Type useable as initializer for embedded/stack-instances*/
#define CONST_C_refTempSimpleClass_TestAnonymous_Test(OBJP) { CONST_ObjectJc(sizeof(C_refTempSimpleClass_TestAnonymous_Test_s), OBJP, &reflection_C_refTempSimpleClass_TestAnonymous_Test_s), 0 }

/**J2C: finalize declaration. It is called by Garbage collector and inside other finalized methods.
 * It should be called by the user if the instance is removed. */
void finalize_C_refTempSimpleClass_TestAnonymous_Test_F(ObjectJc* othis, ThCxt* _thCxt);




/* J2C:Implementation of the method, used for an immediate non-dynamic call: */
METHOD_C int32 addValue_i_C_refTempSimpleClass_TestAnonymous_Test_F(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt);
/* J2C:Call of the method at this class level, executes a dynamic call of the override-able method: */
METHOD_C int32 addValue_i_C_refTempSimpleClass_TestAnonymous_Test(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt);


/* J2C: Method table contains all dynamic linked (virtual) methods
 * of the class and all super classes and interfaces. */
 extern const char sign_Mtbl_C_refTempSimpleClass_TestAnonymous_Test[]; //marker for methodTable check
typedef struct Mtbl_C_refTempSimpleClass_TestAnonymous_Test_t
{ MtblHeadJc head;
  Mtbl_SimpleClass_Test SimpleClass_Test;
} Mtbl_C_refTempSimpleClass_TestAnonymous_Test;



#if defined(__CPLUSPLUSJcpp) && defined(__cplusplus)
/* J2C: The C++-class-definition. */
class C_refTempSimpleClass_TestAnonymous_Test : private C_refTempSimpleClass_TestAnonymous_Test_s
{ public:

  virtual int32 addValue(int32 value){  return addValue_i_C_refTempSimpleClass_TestAnonymous_Test_F(&this->base.super, value,  null/*_thCxt*/); }
};

#endif /*__CPLUSPLUSJcpp*/


/**Default constructor. */
METHOD_C struct C_refTempSimpleClass_TestAnonymous_Test_t* ctorO_C_refTempSimpleClass_TestAnonymous_Test(struct TestAnonymous_Test_t* outer, ObjectJc* othis, int32 value, ThCxt* _thCxt);


/*@CLASS_C C_INNER_TestAnonymous_Test @@@@@@@@@@@@@@@@@@@@@@@@*/

typedef struct C_INNER_TestAnonymous_Test_t
{ 
  union { ObjectJc object; SimpleClass_Test_s super;} base; 
  struct TestAnonymous_Test_t* outer;  //J2C: Reference to outer class, implicit in Java
} C_INNER_TestAnonymous_Test_s;
  

#define sizeof_C_INNER_TestAnonymous_Test_s sizeof(C_INNER_TestAnonymous_Test_s)


/**J2c: Definitions of the enhanced reference. It's conditinally because it may be defined in a included header before. */
#ifndef C_INNER_TestAnonymous_TestREFDEF
  #define C_INNER_TestAnonymous_TestREFDEF
  typedef struct C_INNER_TestAnonymous_TestREF_t { ObjectRefValuesJc refbase; struct C_INNER_TestAnonymous_Test_t* ref; } C_INNER_TestAnonymous_TestREF;
#endif

/**J2c: Definitions of the array forms. NOTE: The number of elements are a helper for debug, the really used number depends on the memory size! */
typedef struct C_INNER_TestAnonymous_Test_X_t { ObjectArrayJc head; C_INNER_TestAnonymous_TestREF data[50]; } C_INNER_TestAnonymous_Test_X;
typedef struct C_INNER_TestAnonymous_Test_Y_t { ObjectArrayJc head; C_INNER_TestAnonymous_Test_s data[50]; } C_INNER_TestAnonymous_Test_Y;

 extern struct ClassJc_t const reflection_C_INNER_TestAnonymous_Test_s;
  


/**CONST_Type useable as initializer for embedded/stack-instances*/
#define CONST_C_INNER_TestAnonymous_Test(OBJP) { CONST_ObjectJc(sizeof(C_INNER_TestAnonymous_Test_s), OBJP, &reflection_C_INNER_TestAnonymous_Test_s), 0 }

/**J2C: finalize declaration. It is called by Garbage collector and inside other finalized methods.
 * It should be called by the user if the instance is removed. */
void finalize_C_INNER_TestAnonymous_Test_F(ObjectJc* othis, ThCxt* _thCxt);




/* J2C:Implementation of the method, used for an immediate non-dynamic call: */
METHOD_C int32 addValue_i_C_INNER_TestAnonymous_Test_F(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt);
/* J2C:Call of the method at this class level, executes a dynamic call of the override-able method: */
METHOD_C int32 addValue_i_C_INNER_TestAnonymous_Test(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt);


/* J2C: Method table contains all dynamic linked (virtual) methods
 * of the class and all super classes and interfaces. */
 extern const char sign_Mtbl_C_INNER_TestAnonymous_Test[]; //marker for methodTable check
typedef struct Mtbl_C_INNER_TestAnonymous_Test_t
{ MtblHeadJc head;
  Mtbl_SimpleClass_Test SimpleClass_Test;
} Mtbl_C_INNER_TestAnonymous_Test;



#if defined(__CPLUSPLUSJcpp) && defined(__cplusplus)
/* J2C: The C++-class-definition. */
class C_INNER_TestAnonymous_Test : private C_INNER_TestAnonymous_Test_s
{ public:

  virtual int32 addValue(int32 value){  return addValue_i_C_INNER_TestAnonymous_Test_F(&this->base.super, value,  null/*_thCxt*/); }
};

#endif /*__CPLUSPLUSJcpp*/


/**Default constructor. */
METHOD_C struct C_INNER_TestAnonymous_Test_t* ctorO_C_INNER_TestAnonymous_Test(struct TestAnonymous_Test_t* outer, ObjectJc* othis, int32 value, ThCxt* _thCxt);


const char sign_Mtbl_TestAnonymous_Test[] = "TestAnonymous_Test"; //to mark method tables of all implementations

typedef struct MtblDef_TestAnonymous_Test_t { Mtbl_TestAnonymous_Test mtbl; MtblHeadJc end; } MtblDef_TestAnonymous_Test;
 extern MtblDef_TestAnonymous_Test const mtblTestAnonymous_Test;

/*Constructor *//**J2C: autogenerated as default constructor. */
struct TestAnonymous_Test_t* ctorO_TestAnonymous_Test(ObjectJc* othis, ThCxt* _thCxt)
{ TestAnonymous_Test_s* ythis = (TestAnonymous_Test_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_TestAnonymous_Test");
  checkConsistence_ObjectJc(othis, sizeof(TestAnonymous_Test_s), null, _thCxt);  
  setReflection_ObjectJc(othis, &reflection_TestAnonymous_Test_s, sizeof(TestAnonymous_Test_s));  
  //j2c: Initialize all class variables:
  {
    ythis->testValueOuter = 34;
    //J2C: constructor for embedded element-ObjectJc
      init_ObjectJc(&(ythis->ref2.base.object), sizeof(ythis->ref2), 0); 
      ctorO_C_ref2_TestAnonymous_Test(ythis, &(ythis->ref2.base.object), 23, _thCxt);
    //J2C: constructor for embedded element-ObjectJc
      init_ObjectJc(&(ythis->staticAnonymous.base.object), sizeof(ythis->staticAnonymous), 0); 
      ctorO_C_staticAnonymous_TestAnonymous_Test(ythis, &(ythis->staticAnonymous.base.object), 23, _thCxt);
  }/*J2C:No body for constructor*/

  STACKTRC_LEAVE;
  return ythis;
}


void setRef_TestAnonymous_Test_F(TestAnonymous_Test_s* ythis, struct SimpleClass_Test_t* ref, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("setRef_TestAnonymous_Test_F");
  
  { 
    
    SETREFJc(ythis->ref, ref, SimpleClass_Test_s);
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
void setRef_TestAnonymous_Test(TestAnonymous_Test_s* ythis, struct SimpleClass_Test_t* ref, ThCxt* _thCxt)
{ Mtbl_TestAnonymous_Test const* mtbl = (Mtbl_TestAnonymous_Test const*)getMtbl_ObjectJc(&ythis->base.object, sign_Mtbl_TestAnonymous_Test);
  mtbl->setRef(ythis, ref, _thCxt);
}


const char sign_Mtbl_C_refTempSimpleClass_TestAnonymous_Test[] = "C_refTempSimpleClass_TestAnonymous_Test"; //to mark method tables of all implementations

typedef struct MtblDef_C_refTempSimpleClass_TestAnonymous_Test_t { Mtbl_C_refTempSimpleClass_TestAnonymous_Test mtbl; MtblHeadJc end; } MtblDef_C_refTempSimpleClass_TestAnonymous_Test;
 extern MtblDef_C_refTempSimpleClass_TestAnonymous_Test const mtblC_refTempSimpleClass_TestAnonymous_Test;
int32 addValue_i_C_refTempSimpleClass_TestAnonymous_Test_F(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt)
{ C_refTempSimpleClass_TestAnonymous_Test_s* ythis = (C_refTempSimpleClass_TestAnonymous_Test_s*)ithis;
  
  STACKTRC_TENTRY("addValue_i_C_refTempSimpleClass_TestAnonymous_Test_F");
  
  { 
    
    ythis->outer->testValueOuter = value;
    ythis->base.super.x1 += value;
    { STACKTRC_LEAVE;
      return ythis->base.super.x1;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
int32 addValue_i_C_refTempSimpleClass_TestAnonymous_Test(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt)
{ Mtbl_SimpleClass_Test const* mtbl = (Mtbl_SimpleClass_Test const*)getMtbl_ObjectJc(&ithis->base.object, sign_Mtbl_SimpleClass_Test);
  return mtbl->addValue((SimpleClass_Test_s*)ithis, value, _thCxt);
}


/*Constructor *//**J2C: autogenerated as default constructor. */
struct C_refTempSimpleClass_TestAnonymous_Test_t* ctorO_C_refTempSimpleClass_TestAnonymous_Test(struct TestAnonymous_Test_t* outer, ObjectJc* othis, int32 value, ThCxt* _thCxt)
{ C_refTempSimpleClass_TestAnonymous_Test_s* ythis = (C_refTempSimpleClass_TestAnonymous_Test_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_C_refTempSimpleClass_TestAnonymous_Test");
  checkConsistence_ObjectJc(othis, sizeof(C_refTempSimpleClass_TestAnonymous_Test_s), null, _thCxt);  
  //J2C:super Constructor
  ctorO_i_SimpleClass_Test(&ythis->base.object, value, _thCxt);
  setReflection_ObjectJc(othis, &reflection_C_refTempSimpleClass_TestAnonymous_Test_s, sizeof(C_refTempSimpleClass_TestAnonymous_Test_s));  
  ythis->outer = outer;
  //j2c: Initialize all class variables:
  {
  }/*J2C:No body for constructor*/

  STACKTRC_LEAVE;
  return ythis;
}




/**J2C: Reflections and Method-table *************************************************/
const MtblDef_C_refTempSimpleClass_TestAnonymous_Test mtblC_refTempSimpleClass_TestAnonymous_Test = {
{ { sign_Mtbl_C_refTempSimpleClass_TestAnonymous_Test//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_SimpleClass_Test//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((2 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , addValue_i_C_refTempSimpleClass_TestAnonymous_Test_F //addValue
  , getValue_SimpleClass_Test_F //getValue
  , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , clone_ObjectJc_F //clone
    , equals_ObjectJc_F //equals
    , finalize_SimpleClass_Test_F //finalize
    , hashCode_ObjectJc_F //hashCode
    , toString_ObjectJc_F //toString
    }
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_SimpleClass_Test_s;
 static struct superClasses_C_refTempSimpleClass_TestAnonymous_Test_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_C_refTempSimpleClass_TestAnonymous_Test_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_SimpleClass_Test_s, OFFSET_Mtbl(Mtbl_C_refTempSimpleClass_TestAnonymous_Test, SimpleClass_Test) }
   }
 };

const ClassJc reflection_C_refTempSimpleClass_TestAnonymous_Test_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "C_refTempSimpleCla_us_Test_s"
,  0 //position of ObjectJc
, sizeof(C_refTempSimpleClass_TestAnonymous_Test_s)
, null //attributes and associations
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_C_refTempSimpleClass_TestAnonymous_Test_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblC_refTempSimpleClass_TestAnonymous_Test.mtbl.head
};


const char sign_Mtbl_C_INNER_TestAnonymous_Test[] = "C_INNER_TestAnonymous_Test"; //to mark method tables of all implementations

typedef struct MtblDef_C_INNER_TestAnonymous_Test_t { Mtbl_C_INNER_TestAnonymous_Test mtbl; MtblHeadJc end; } MtblDef_C_INNER_TestAnonymous_Test;
 extern MtblDef_C_INNER_TestAnonymous_Test const mtblC_INNER_TestAnonymous_Test;
int32 addValue_i_C_INNER_TestAnonymous_Test_F(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt)
{ C_INNER_TestAnonymous_Test_s* ythis = (C_INNER_TestAnonymous_Test_s*)ithis;
  
  STACKTRC_TENTRY("addValue_i_C_INNER_TestAnonymous_Test_F");
  
  { 
    
    ythis->base.super.x1 -= value;//other operation.
    
    ythis->base.super.x1 += ythis->outer->testValueOuter;////access to an value of the outer class.
    
    { STACKTRC_LEAVE;
      return ythis->base.super.x1;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
int32 addValue_i_C_INNER_TestAnonymous_Test(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt)
{ Mtbl_SimpleClass_Test const* mtbl = (Mtbl_SimpleClass_Test const*)getMtbl_ObjectJc(&ithis->base.object, sign_Mtbl_SimpleClass_Test);
  return mtbl->addValue((SimpleClass_Test_s*)ithis, value, _thCxt);
}


/*Constructor *//**J2C: autogenerated as default constructor. */
struct C_INNER_TestAnonymous_Test_t* ctorO_C_INNER_TestAnonymous_Test(struct TestAnonymous_Test_t* outer, ObjectJc* othis, int32 value, ThCxt* _thCxt)
{ C_INNER_TestAnonymous_Test_s* ythis = (C_INNER_TestAnonymous_Test_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_C_INNER_TestAnonymous_Test");
  checkConsistence_ObjectJc(othis, sizeof(C_INNER_TestAnonymous_Test_s), null, _thCxt);  
  //J2C:super Constructor
  ctorO_i_SimpleClass_Test(&ythis->base.object, value, _thCxt);
  setReflection_ObjectJc(othis, &reflection_C_INNER_TestAnonymous_Test_s, sizeof(C_INNER_TestAnonymous_Test_s));  
  ythis->outer = outer;
  //j2c: Initialize all class variables:
  {
  }/*J2C:No body for constructor*/

  STACKTRC_LEAVE;
  return ythis;
}




/**J2C: Reflections and Method-table *************************************************/
const MtblDef_C_INNER_TestAnonymous_Test mtblC_INNER_TestAnonymous_Test = {
{ { sign_Mtbl_C_INNER_TestAnonymous_Test//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_SimpleClass_Test//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((2 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , addValue_i_C_INNER_TestAnonymous_Test_F //addValue
  , getValue_SimpleClass_Test_F //getValue
  , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , clone_ObjectJc_F //clone
    , equals_ObjectJc_F //equals
    , finalize_SimpleClass_Test_F //finalize
    , hashCode_ObjectJc_F //hashCode
    , toString_ObjectJc_F //toString
    }
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_SimpleClass_Test_s;
 static struct superClasses_C_INNER_TestAnonymous_Test_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_C_INNER_TestAnonymous_Test_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_SimpleClass_Test_s, OFFSET_Mtbl(Mtbl_C_INNER_TestAnonymous_Test, SimpleClass_Test) }
   }
 };

const ClassJc reflection_C_INNER_TestAnonymous_Test_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "C_INNER_TestAnonymous_Test_s"
,  0 //position of ObjectJc
, sizeof(C_INNER_TestAnonymous_Test_s)
, null //attributes and associations
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_C_INNER_TestAnonymous_Test_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblC_INNER_TestAnonymous_Test.mtbl.head
};

void test_TestAnonymous_Test_F(TestAnonymous_Test_s* ythis, ThCxt* _thCxt)
{ Mtbl_TestAnonymous_Test const* mtthis = (Mtbl_TestAnonymous_Test const*)getMtbl_ObjectJc(&ythis->base.object, sign_Mtbl_TestAnonymous_Test);
  
  STACKTRC_TENTRY("test_TestAnonymous_Test_F");
  
  { 
    int32 testvalue1 = 212; 
    C_refTempSimpleClass_TestAnonymous_Test_s refTempSimpleClass = { 0 }; 
    
    ObjectJc *newObj1_1=null; //J2C: temporary Objects for new operations
     //J2C: temporary Stringbuffer for String concatenation
    StringBuilderJc* _tempString1_1=null; 
    
    testvalue1 = 212;
    
    //J2C: constructor for embedded element-ObjectJc
    init_ObjectJc(&(refTempSimpleClass.base.object), sizeof(refTempSimpleClass), 0); 
    ctorO_C_refTempSimpleClass_TestAnonymous_Test(ythis, &(refTempSimpleClass.base.object), 12, _thCxt);
    addValue_i_C_refTempSimpleClass_TestAnonymous_Test_F(& ((refTempSimpleClass).base.super), 43, _thCxt);//test of a anonymous class definition inside the expression for a parameter of a method.
    
    mtthis->setRef(ythis, & ((* (ctorO_C_INNER_TestAnonymous_Test(ythis, (newObj1_1 = alloc_ObjectJc(sizeof_C_INNER_TestAnonymous_Test_s, 0, _thCxt)), 34, _thCxt))).base.super), _thCxt);
    { int32 x; 
      for(x = 0; x < 100; x++)
        { 
          
          ((Mtbl_SimpleClass_Test const*)getMtbl_ObjectJc(&(REFJc(ythis->ref))->base.object, sign_Mtbl_SimpleClass_Test) )->addValue(REFJc(ythis->ref), x, _thCxt);//calls the method above....
          
          addValue_i_C_ref2_TestAnonymous_Test_F(& ((ythis->ref2).base.super.base.super), x, _thCxt);
          addValue_i_C_staticAnonymous_TestAnonymous_Test_F(& ((ythis->staticAnonymous).base.super), x, _thCxt);
        }
    }
    println_s_PrintStreamJc(REFJc(out_SystemJc), 
      ( _tempString1_1 = new_StringBuilderJc(-1, _thCxt)
      , setStringConcatBuffer_StringBuilderJc(_tempString1_1)
      , append_z_StringBuilderJc(_tempString1_1, "TestAnonymous ", _thCxt)
      , append_I_StringBuilderJc(_tempString1_1, getValue_SimpleClass_Test_F(& ((ythis->staticAnonymous).base.super), _thCxt), _thCxt)
      , toString_StringBuilderJc(&(_tempString1_1)->base.object, _thCxt)
      ), _thCxt);
    activateGarbageCollectorAccess_BlockHeapJc(newObj1_1, null);
    activateGarbageCollectorAccess_BlockHeapJc(&_tempString1_1->base.object, null);
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
void test_TestAnonymous_Test(TestAnonymous_Test_s* ythis, ThCxt* _thCxt)
{ Mtbl_TestAnonymous_Test const* mtbl = (Mtbl_TestAnonymous_Test const*)getMtbl_ObjectJc(&ythis->base.object, sign_Mtbl_TestAnonymous_Test);
  mtbl->test(ythis, _thCxt);
}


void finalize_TestAnonymous_Test_F(ObjectJc* othis, ThCxt* _thCxt)
{ TestAnonymous_Test_s* ythis = (TestAnonymous_Test_s*)othis;  //upcasting to the real class.
 STACKTRC_TENTRY("finalize_TestAnonymous_Test_F");
  CLEAR_REFJc(ythis->ref);
  finalize_ImplIfcTest_F(&ythis->ref2.base.object, _thCxt); //J2C: finalizing the embedded instance.
  finalize_SimpleClass_Test_F(&ythis->staticAnonymous.base.object, _thCxt); //J2C: finalizing the embedded instance.
  finalize_ObjectJc_F(&ythis->base.object, _thCxt); //J2C: finalizing the superclass.
  STACKTRC_LEAVE;
}




/**J2C: Reflections and Method-table *************************************************/
const MtblDef_TestAnonymous_Test mtblTestAnonymous_Test = {
{ { sign_Mtbl_TestAnonymous_Test//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((2 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, setRef_TestAnonymous_Test_F //setRef
, test_TestAnonymous_Test_F //test
, { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , clone_ObjectJc_F //clone
  , equals_ObjectJc_F //equals
  , finalize_TestAnonymous_Test_F //finalize
  , hashCode_ObjectJc_F //hashCode
  , toString_ObjectJc_F //toString
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_ObjectJc;
 static struct superClasses_TestAnonymous_Test_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_TestAnonymous_Test_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ObjectJc, OFFSET_Mtbl(Mtbl_TestAnonymous_Test, ObjectJc) }
   }
 };

extern struct ClassJc_t const reflection_TestAnonymous_Test_s;
extern struct ClassJc_t const reflection_C_ref2_TestAnonymous_Test_s;
extern struct ClassJc_t const reflection_C_staticAnonymous_TestAnonymous_Test_s;
extern struct ClassJc_t const reflection_SimpleClass_Test_s;
const struct Reflection_Fields_TestAnonymous_Test_s_t
{ ObjectArrayJc head; FieldJc data[4];
} reflection_Fields_TestAnonymous_Test_s =
{ CONST_ObjectArrayJc(FieldJc, 4, OBJTYPE_FieldJc, null, &reflection_Fields_TestAnonymous_Test_s)
, {
     { "testValueOuter"
    , 0 //nrofArrayElements
    , REFLECTION_int32
    , 4 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((TestAnonymous_Test_s*)(0x1000))->testValueOuter) - (int32)(TestAnonymous_Test_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_TestAnonymous_Test_s
    }
   , { "ref"
    , 0 //nrofArrayElements
    , &reflection_SimpleClass_Test_s
    , kEnhancedReference_Modifier_reflectJc /*@*/ |mObjectJc_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((TestAnonymous_Test_s*)(0x1000))->ref) - (int32)(TestAnonymous_Test_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_TestAnonymous_Test_s
    }
   , { "ref2"
    , 0 //nrofArrayElements
    , &reflection_C_ref2_TestAnonymous_Test_s
    , kEmbedded_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((TestAnonymous_Test_s*)(0x1000))->ref2) - (int32)(TestAnonymous_Test_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_TestAnonymous_Test_s
    }
   , { "staticAnonymous"
    , 0 //nrofArrayElements
    , &reflection_C_staticAnonymous_TestAnonymous_Test_s
    , kEmbedded_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((TestAnonymous_Test_s*)(0x1000))->staticAnonymous) - (int32)(TestAnonymous_Test_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_TestAnonymous_Test_s
    }
} };
const ClassJc reflection_TestAnonymous_Test_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "TestAnonymous_Test_s"
,  0 //position of ObjectJc
, sizeof(TestAnonymous_Test_s)
, (FieldJcArray const*)&reflection_Fields_TestAnonymous_Test_s
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_TestAnonymous_Test_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblTestAnonymous_Test.mtbl.head
};


const char sign_Mtbl_TestInnerNonstatic_TestAnonymous_Test[] = "TestInnerNonstatic_TestAnonymous_Test"; //to mark method tables of all implementations

typedef struct MtblDef_TestInnerNonstatic_TestAnonymous_Test_t { Mtbl_TestInnerNonstatic_TestAnonymous_Test mtbl; MtblHeadJc end; } MtblDef_TestInnerNonstatic_TestAnonymous_Test;
 extern MtblDef_TestInnerNonstatic_TestAnonymous_Test const mtblTestInnerNonstatic_TestAnonymous_Test;

/*Constructor *//**J2C: autogenerated as default constructor. */
struct TestInnerNonstatic_TestAnonymous_Test_t* ctorO_TestInnerNonstatic_TestAnonymous_Test(struct TestAnonymous_Test_t* outer, ObjectJc* othis, ThCxt* _thCxt)
{ TestInnerNonstatic_TestAnonymous_Test_s* ythis = (TestInnerNonstatic_TestAnonymous_Test_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_TestInnerNonstatic_TestAnonymous_Test");
  checkConsistence_ObjectJc(othis, sizeof(TestInnerNonstatic_TestAnonymous_Test_s), null, _thCxt);  
  setReflection_ObjectJc(othis, &reflection_TestInnerNonstatic_TestAnonymous_Test_s, sizeof(TestInnerNonstatic_TestAnonymous_Test_s));  
  ythis->outer = outer;
  //j2c: Initialize all class variables:
  {
  }/*J2C:No body for constructor*/

  STACKTRC_LEAVE;
  return ythis;
}


void testInnerNonstatic_TestInnerNonstatic_TestAnonymous_Test(TestInnerNonstatic_TestAnonymous_Test_s* ythis, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("testInnerNonstatic_TestInnerNonstatic_TestAnonymous_Test");
  
  { 
    
    ythis->outer->testValueOuter = ythis->xInnerNonstatic;//
    
  }
  STACKTRC_LEAVE;
}



/**J2C: Reflections and Method-table *************************************************/
const MtblDef_TestInnerNonstatic_TestAnonymous_Test mtblTestInnerNonstatic_TestAnonymous_Test = {
{ { sign_Mtbl_TestInnerNonstatic_TestAnonymous_Test//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , clone_ObjectJc_F //clone
  , equals_ObjectJc_F //equals
  , finalize_ObjectJc_F //finalize
  , hashCode_ObjectJc_F //hashCode
  , toString_ObjectJc_F //toString
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_ObjectJc;
 static struct superClasses_TestInnerNonstatic_TestAnonymous_Test_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_TestInnerNonstatic_TestAnonymous_Test_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ObjectJc, OFFSET_Mtbl(Mtbl_TestInnerNonstatic_TestAnonymous_Test, ObjectJc) }
   }
 };

extern struct ClassJc_t const reflection_TestInnerNonstatic_TestAnonymous_Test_s;
extern struct ClassJc_t const reflection_C_ref2_TestAnonymous_Test_s;
extern struct ClassJc_t const reflection_C_staticAnonymous_TestAnonymous_Test_s;
extern struct ClassJc_t const reflection_SimpleClass_Test_s;
const struct Reflection_Fields_TestInnerNonstatic_TestAnonymous_Test_s_t
{ ObjectArrayJc head; FieldJc data[1];
} reflection_Fields_TestInnerNonstatic_TestAnonymous_Test_s =
{ CONST_ObjectArrayJc(FieldJc, 1, OBJTYPE_FieldJc, null, &reflection_Fields_TestInnerNonstatic_TestAnonymous_Test_s)
, {
     { "xInnerNonstatic"
    , 0 //nrofArrayElements
    , REFLECTION_int32
    , 4 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((TestInnerNonstatic_TestAnonymous_Test_s*)(0x1000))->xInnerNonstatic) - (int32)(TestInnerNonstatic_TestAnonymous_Test_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_TestInnerNonstatic_TestAnonymous_Test_s
    }
} };
const ClassJc reflection_TestInnerNonstatic_TestAnonymous_Test_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "TestInnerNonstatic_us_Test_s"
,  0 //position of ObjectJc
, sizeof(TestInnerNonstatic_TestAnonymous_Test_s)
, (FieldJcArray const*)&reflection_Fields_TestInnerNonstatic_TestAnonymous_Test_s
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_TestInnerNonstatic_TestAnonymous_Test_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblTestInnerNonstatic_TestAnonymous_Test.mtbl.head
};


const char sign_Mtbl_TestInnerStatic_TestAnonymous_Test[] = "TestInnerStatic_TestAnonymous_Test"; //to mark method tables of all implementations

typedef struct MtblDef_TestInnerStatic_TestAnonymous_Test_t { Mtbl_TestInnerStatic_TestAnonymous_Test mtbl; MtblHeadJc end; } MtblDef_TestInnerStatic_TestAnonymous_Test;
 extern MtblDef_TestInnerStatic_TestAnonymous_Test const mtblTestInnerStatic_TestAnonymous_Test;

/*Constructor *//**J2C: autogenerated as default constructor. */
struct TestInnerStatic_TestAnonymous_Test_t* ctorO_TestInnerStatic_TestAnonymous_Test(ObjectJc* othis, ThCxt* _thCxt)
{ TestInnerStatic_TestAnonymous_Test_s* ythis = (TestInnerStatic_TestAnonymous_Test_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_TestInnerStatic_TestAnonymous_Test");
  checkConsistence_ObjectJc(othis, sizeof(TestInnerStatic_TestAnonymous_Test_s), null, _thCxt);  
  setReflection_ObjectJc(othis, &reflection_TestInnerStatic_TestAnonymous_Test_s, sizeof(TestInnerStatic_TestAnonymous_Test_s));  
  //j2c: Initialize all class variables:
  {
  }/*J2C:No body for constructor*/

  STACKTRC_LEAVE;
  return ythis;
}


void testInnerNonstatic_TestInnerStatic_TestAnonymous_Test(TestInnerStatic_TestAnonymous_Test_s* ythis, int32 input, ThCxt* _thCxt)
{ 
  STACKTRC_TENTRY("testInnerNonstatic_TestInnerStatic_TestAnonymous_Test");
  
  { 
    
    ythis->xInnerStatic = input;
  }
  STACKTRC_LEAVE;
}



/**J2C: Reflections and Method-table *************************************************/
const MtblDef_TestInnerStatic_TestAnonymous_Test mtblTestInnerStatic_TestAnonymous_Test = {
{ { sign_Mtbl_TestInnerStatic_TestAnonymous_Test//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , clone_ObjectJc_F //clone
  , equals_ObjectJc_F //equals
  , finalize_ObjectJc_F //finalize
  , hashCode_ObjectJc_F //hashCode
  , toString_ObjectJc_F //toString
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_ObjectJc;
 static struct superClasses_TestInnerStatic_TestAnonymous_Test_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_TestInnerStatic_TestAnonymous_Test_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ObjectJc, OFFSET_Mtbl(Mtbl_TestInnerStatic_TestAnonymous_Test, ObjectJc) }
   }
 };

extern struct ClassJc_t const reflection_TestInnerStatic_TestAnonymous_Test_s;
const struct Reflection_Fields_TestInnerStatic_TestAnonymous_Test_s_t
{ ObjectArrayJc head; FieldJc data[1];
} reflection_Fields_TestInnerStatic_TestAnonymous_Test_s =
{ CONST_ObjectArrayJc(FieldJc, 1, OBJTYPE_FieldJc, null, &reflection_Fields_TestInnerStatic_TestAnonymous_Test_s)
, {
     { "xInnerStatic"
    , 0 //nrofArrayElements
    , REFLECTION_int32
    , 4 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((TestInnerStatic_TestAnonymous_Test_s*)(0x1000))->xInnerStatic) - (int32)(TestInnerStatic_TestAnonymous_Test_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_TestInnerStatic_TestAnonymous_Test_s
    }
} };
const ClassJc reflection_TestInnerStatic_TestAnonymous_Test_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "TestInnerStatic_Te_us_Test_s"
,  0 //position of ObjectJc
, sizeof(TestInnerStatic_TestAnonymous_Test_s)
, (FieldJcArray const*)&reflection_Fields_TestInnerStatic_TestAnonymous_Test_s
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_TestInnerStatic_TestAnonymous_Test_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblTestInnerStatic_TestAnonymous_Test.mtbl.head
};


const char sign_Mtbl_C_ref2_TestAnonymous_Test[] = "C_ref2_TestAnonymous_Test"; //to mark method tables of all implementations

typedef struct MtblDef_C_ref2_TestAnonymous_Test_t { Mtbl_C_ref2_TestAnonymous_Test mtbl; MtblHeadJc end; } MtblDef_C_ref2_TestAnonymous_Test;
 extern MtblDef_C_ref2_TestAnonymous_Test const mtblC_ref2_TestAnonymous_Test;
int32 addValue_i_C_ref2_TestAnonymous_Test_F(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt)
{ C_ref2_TestAnonymous_Test_s* ythis = (C_ref2_TestAnonymous_Test_s*)ithis;
  
  STACKTRC_TENTRY("addValue_i_C_ref2_TestAnonymous_Test_F");
  
  { 
    
    ythis->base.super.base.super.x1 += ythis->outer->testValueOuter * value;////access to an value of the outer class.
    
    { STACKTRC_LEAVE;
      return ythis->base.super.base.super.x1;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
int32 addValue_i_C_ref2_TestAnonymous_Test(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt)
{ Mtbl_SimpleClass_Test const* mtbl = (Mtbl_SimpleClass_Test const*)getMtbl_ObjectJc(&ithis->base.object, sign_Mtbl_SimpleClass_Test);
  return mtbl->addValue((SimpleClass_Test_s*)ithis, value, _thCxt);
}


/*Constructor *//**J2C: autogenerated as default constructor. */
struct C_ref2_TestAnonymous_Test_t* ctorO_C_ref2_TestAnonymous_Test(struct TestAnonymous_Test_t* outer, ObjectJc* othis, int32 val, ThCxt* _thCxt)
{ C_ref2_TestAnonymous_Test_s* ythis = (C_ref2_TestAnonymous_Test_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_C_ref2_TestAnonymous_Test");
  checkConsistence_ObjectJc(othis, sizeof(C_ref2_TestAnonymous_Test_s), null, _thCxt);  
  //J2C:super Constructor
  ctorO_ImplIfcTest(&ythis->base.object, val, _thCxt);
  setReflection_ObjectJc(othis, &reflection_C_ref2_TestAnonymous_Test_s, sizeof(C_ref2_TestAnonymous_Test_s));  
  ythis->outer = outer;
  //j2c: Initialize all class variables:
  {
  }/*J2C:No body for constructor*/

  STACKTRC_LEAVE;
  return ythis;
}




/**J2C: Reflections and Method-table *************************************************/
const MtblDef_C_ref2_TestAnonymous_Test mtblC_ref2_TestAnonymous_Test = {
{ { sign_Mtbl_C_ref2_TestAnonymous_Test//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_ImplIfcTest//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((4 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , testOverrideAble_ImplIfcTest_F //testOverrideAble
  , testOverridden_ImplIfcTest_F //testOverridden
  , returnThisOverrideable_ImplIfcTest_F //returnThisOverrideable
  , returnAnyInstanceOverrideable_ImplIfcTest_F //returnAnyInstanceOverrideable
  , { { sign_Mtbl_SimpleClass_Test//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((2 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , addValue_i_C_ref2_TestAnonymous_Test_F //addValue
    , getValue_SimpleClass_Test_F //getValue
    , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
        , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
        }
      , clone_ObjectJc_F //clone
      , equals_ObjectJc_F //equals
      , finalize_ImplIfcTest_F //finalize
      , hashCode_ObjectJc_F //hashCode
      , toString_ImplIfcTest_F //toString
      }
    }
    /**J2C: Mtbl-interfaces of C_ref2_TestAnonymous_Test: */
  , { { sign_Mtbl_IfcToTest//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((3 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , processIfcMethod_i_ImplIfcTest_F //processIfcMethod
    , anotherIfcmethod_i_ImplIfcTest //anotherIfcmethod_i
    , anotherIfcmethod_f_ImplIfcTest_F //anotherIfcmethod_f
    , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
        , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
        }
      , clone_ObjectJc_F //clone
      , equals_ObjectJc_F //equals
      , finalize_ImplIfcTest_F //finalize
      , hashCode_ObjectJc_F //hashCode
      , toString_ImplIfcTest_F //toString
      }
    }
  , { { sign_Mtbl_Ifc2_Test//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((3 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , processIfcMethod_f_ImplIfcTest //processIfcMethod
    , testIfc2_f_ImplIfcTest //testIfc2
    , anotherIfcmethod_f_ImplIfcTest_F //anotherIfcmethod
    , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
        , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
        }
      , clone_ObjectJc_F //clone
      , equals_ObjectJc_F //equals
      , finalize_ImplIfcTest_F //finalize
      , hashCode_ObjectJc_F //hashCode
      , toString_ImplIfcTest_F //toString
      }
    }
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_ImplIfcTest_s;
 static struct superClasses_C_ref2_TestAnonymous_Test_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_C_ref2_TestAnonymous_Test_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ImplIfcTest_s, OFFSET_Mtbl(Mtbl_C_ref2_TestAnonymous_Test, ImplIfcTest) }
   }
 };

const ClassJc reflection_C_ref2_TestAnonymous_Test_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "C_ref2_TestAnonymous_Test_s"
,  0 //position of ObjectJc
, sizeof(C_ref2_TestAnonymous_Test_s)
, null //attributes and associations
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_C_ref2_TestAnonymous_Test_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblC_ref2_TestAnonymous_Test.mtbl.head
};


const char sign_Mtbl_C_staticAnonymous_TestAnonymous_Test[] = "C_staticAnonymous_TestAnonymous_Test"; //to mark method tables of all implementations

typedef struct MtblDef_C_staticAnonymous_TestAnonymous_Test_t { Mtbl_C_staticAnonymous_TestAnonymous_Test mtbl; MtblHeadJc end; } MtblDef_C_staticAnonymous_TestAnonymous_Test;
 extern MtblDef_C_staticAnonymous_TestAnonymous_Test const mtblC_staticAnonymous_TestAnonymous_Test;
int32 addValue_i_C_staticAnonymous_TestAnonymous_Test_F(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt)
{ C_staticAnonymous_TestAnonymous_Test_s* ythis = (C_staticAnonymous_TestAnonymous_Test_s*)ithis;
  
  STACKTRC_TENTRY("addValue_i_C_staticAnonymous_TestAnonymous_Test_F");
  
  { 
    
    ythis->disturbing = (float)random_MathJc() - 0.5F;
    ythis->x1 += value + ythis->disturbing;//access to an value of the outer class.
    
    (&ythis->base.super)->x1 = (int32)ythis->x1;
    { STACKTRC_LEAVE;
      return (&ythis->base.super)->x1;
    }
  }
  STACKTRC_LEAVE;
}

/*J2C: dynamic call variant of the override-able method: */
int32 addValue_i_C_staticAnonymous_TestAnonymous_Test(SimpleClass_Test_s* ithis, int32 value, ThCxt* _thCxt)
{ Mtbl_SimpleClass_Test const* mtbl = (Mtbl_SimpleClass_Test const*)getMtbl_ObjectJc(&ithis->base.object, sign_Mtbl_SimpleClass_Test);
  return mtbl->addValue((SimpleClass_Test_s*)ithis, value, _thCxt);
}


/*Constructor *//**J2C: autogenerated as default constructor. */
struct C_staticAnonymous_TestAnonymous_Test_t* ctorO_C_staticAnonymous_TestAnonymous_Test(struct TestAnonymous_Test_t* outer, ObjectJc* othis, int32 value, ThCxt* _thCxt)
{ C_staticAnonymous_TestAnonymous_Test_s* ythis = (C_staticAnonymous_TestAnonymous_Test_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_C_staticAnonymous_TestAnonymous_Test");
  checkConsistence_ObjectJc(othis, sizeof(C_staticAnonymous_TestAnonymous_Test_s), null, _thCxt);  
  //J2C:super Constructor
  ctorO_i_SimpleClass_Test(&ythis->base.object, value, _thCxt);
  setReflection_ObjectJc(othis, &reflection_C_staticAnonymous_TestAnonymous_Test_s, sizeof(C_staticAnonymous_TestAnonymous_Test_s));  
  ythis->outer = outer;
  //j2c: Initialize all class variables:
  {
  }/*J2C:No body for constructor*/

  STACKTRC_LEAVE;
  return ythis;
}




/**J2C: Reflections and Method-table *************************************************/
const MtblDef_C_staticAnonymous_TestAnonymous_Test mtblC_staticAnonymous_TestAnonymous_Test = {
{ { sign_Mtbl_C_staticAnonymous_TestAnonymous_Test//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_SimpleClass_Test//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((2 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , addValue_i_C_staticAnonymous_TestAnonymous_Test_F //addValue
  , getValue_SimpleClass_Test_F //getValue
  , { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
      , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
      }
    , clone_ObjectJc_F //clone
    , equals_ObjectJc_F //equals
    , finalize_SimpleClass_Test_F //finalize
    , hashCode_ObjectJc_F //hashCode
    , toString_ObjectJc_F //toString
    }
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_SimpleClass_Test_s;
 static struct superClasses_C_staticAnonymous_TestAnonymous_Test_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_C_staticAnonymous_TestAnonymous_Test_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_SimpleClass_Test_s, OFFSET_Mtbl(Mtbl_C_staticAnonymous_TestAnonymous_Test, SimpleClass_Test) }
   }
 };

extern struct ClassJc_t const reflection_C_staticAnonymous_TestAnonymous_Test_s;
extern struct ClassJc_t const reflection_C_ref2_TestAnonymous_Test_s;
extern struct ClassJc_t const reflection_C_staticAnonymous_TestAnonymous_Test_s;
extern struct ClassJc_t const reflection_SimpleClass_Test_s;
const struct Reflection_Fields_C_staticAnonymous_TestAnonymous_Test_s_t
{ ObjectArrayJc head; FieldJc data[2];
} reflection_Fields_C_staticAnonymous_TestAnonymous_Test_s =
{ CONST_ObjectArrayJc(FieldJc, 2, OBJTYPE_FieldJc, null, &reflection_Fields_C_staticAnonymous_TestAnonymous_Test_s)
, {
     { "disturbing"
    , 0 //nrofArrayElements
    , REFLECTION_float
    , 4 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((C_staticAnonymous_TestAnonymous_Test_s*)(0x1000))->disturbing) - (int32)(C_staticAnonymous_TestAnonymous_Test_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_C_staticAnonymous_TestAnonymous_Test_s
    }
   , { "x1"
    , 0 //nrofArrayElements
    , REFLECTION_float
    , 4 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((C_staticAnonymous_TestAnonymous_Test_s*)(0x1000))->x1) - (int32)(C_staticAnonymous_TestAnonymous_Test_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_C_staticAnonymous_TestAnonymous_Test_s
    }
} };
const ClassJc reflection_C_staticAnonymous_TestAnonymous_Test_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "C_staticAnonymous__us_Test_s"
,  0 //position of ObjectJc
, sizeof(C_staticAnonymous_TestAnonymous_Test_s)
, (FieldJcArray const*)&reflection_Fields_C_staticAnonymous_TestAnonymous_Test_s
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_C_staticAnonymous_TestAnonymous_Test_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblC_staticAnonymous_TestAnonymous_Test.mtbl.head
};
