/**************************************************************************
 * This file is generated by Java2C
 **copyright***************************************************************
 *************************************************************************/
#include "TestVaArg_Test.h"
#include <string.h>  //because using memset()
#include <Jc/ReflectionJc.h>   //Reflection concept 
#include <Fwc/fw_Exception.h>  //basic stacktrace concept


const char sign_Mtbl_TestVaArg_Test[] = "TestVaArg_Test"; //to mark method tables of all implementations

typedef struct MtblDef_TestVaArg_Test_t { Mtbl_TestVaArg_Test mtbl; MtblHeadJc end; } MtblDef_TestVaArg_Test;
 extern MtblDef_TestVaArg_Test const mtblTestVaArg_Test;

/*Constructor *//**J2C: autogenerated as default constructor. */
struct TestVaArg_Test_t* ctorO_TestVaArg_Test(ObjectJc* othis, ThCxt* _thCxt)
{ TestVaArg_Test_s* ythis = (TestVaArg_Test_s*)othis;  //upcasting to the real class.
  STACKTRC_TENTRY("ctorO_TestVaArg_Test");
  checkConsistence_ObjectJc(othis, sizeof(TestVaArg_Test_s), null, _thCxt);  
  setReflection_ObjectJc(othis, &reflection_TestVaArg_Test_s, sizeof(TestVaArg_Test_s));  
  //j2c: Initialize all class variables:
  {
  }/*J2C:No body for constructor*/

  STACKTRC_LEAVE;
  return ythis;
}




/**J2C: Reflections and Method-table *************************************************/
const MtblDef_TestVaArg_Test mtblTestVaArg_Test = {
{ { sign_Mtbl_TestVaArg_Test//J2C: Head of methodtable.
  , (struct Size_Mtbl_t*)((0 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
  }
, { { sign_Mtbl_ObjectJc//J2C: Head of methodtable.
    , (struct Size_Mtbl_t*)((5 +2) * sizeof(void*)) //size. NOTE: all elements are standard-pointer-types.
    }
  , clone_ObjectJc_F //clone
  , equals_ObjectJc_F //equals
  , finalize_ObjectJc_F //finalize
  , hashCode_ObjectJc_F //hashCode
  , toString_ObjectJc_F //toString
  }
}, { signEnd_Mtbl_ObjectJc, null } }; //Mtbl


 extern struct ClassJc_t const reflection_ObjectJc;
 static struct superClasses_TestVaArg_Test_s_t
 { ObjectArrayJc head;
   ClassOffset_idxMtblJc data[1];
 }superclasses_TestVaArg_Test_s =
 { CONST_ObjectArrayJc(ClassOffset_idxMtblJc, 1, OBJTYPE_ClassOffset_idxMtblJc, null, null)
 , { {&reflection_ObjectJc, OFFSET_Mtbl(Mtbl_TestVaArg_Test, ObjectJc) }
   }
 };

extern struct ClassJc_t const reflection_TestVaArg_Test_s;
const struct Reflection_Fields_TestVaArg_Test_s_t
{ ObjectArrayJc head; FieldJc data[1];
} reflection_Fields_TestVaArg_Test_s =
{ CONST_ObjectArrayJc(FieldJc, 1, OBJTYPE_FieldJc, null, &reflection_Fields_TestVaArg_Test_s)
, {
     { "dummy"
    , 0 //nrofArrayElements
    , REFLECTION_int32
    , 4 << kBitPrimitiv_Modifier_reflectJc //bitModifiers
    , (int16)((int32)(&((TestVaArg_Test_s*)(0x1000))->dummy) - (int32)(TestVaArg_Test_s*)0x1000)
    , 0  //offsetToObjectifcBase
    , &reflection_TestVaArg_Test_s
    }
} };
const ClassJc reflection_TestVaArg_Test_s = 
{ CONST_ObjectJc(OBJTYPE_ClassJc + sizeof(ClassJc), &reflection_ObjectJc, &reflection_ClassJc) 
, "TestVaArg_Test_s"
,  0 //position of ObjectJc
, sizeof(TestVaArg_Test_s)
, (FieldJcArray const*)&reflection_Fields_TestVaArg_Test_s
, null //method
, (ClassOffset_idxMtblJcARRAY*)&superclasses_TestVaArg_Test_s //superclass
, null //interfaces
, 0    //modifiers
, &mtblTestVaArg_Test.mtbl.head
};
